Option Explicit

' ================================================================
' CATIA_VISUAL_BOM_EXPORTER
' CATIA V5 VBA macro for Product Tree / Visual BOM export to Excel.
' Paste this whole module into CATIA V5 VBA editor and run:
'     CATIA_VISUAL_BOM_EXPORTER
' ================================================================

' ---------------------- CONFIGURATION ---------------------------
Private Const IMAGE_FORMAT As String = "png"
Private Const EXPORT_PARTS As Boolean = True
Private Const EXPORT_ASSEMBLIES As Boolean = True
Private Const EXPORT_SELECTED_ONLY As Boolean = False
Private Const IMAGE_WIDTH As Long = 1200
Private Const IMAGE_HEIGHT As Long = 900
Private Const INSERT_IMAGES_IN_EXCEL As Boolean = True
Private Const OUTPUT_TO_DESKTOP As Boolean = True

' CATIA VisProperties show constants.
Private Const CAT_VIS_PROPERTY_SHOW As Long = 0
Private Const CAT_VIS_PROPERTY_NO_SHOW As Long = 1

' CATIA capture formats. CATIA V5 Automation reliably supports BMP/JPEG/TIFF.
' PNG is generated by capturing BMP first and converting it through Windows WIA.
Private Const CAT_CAPTURE_FORMAT_BMP As Long = 0
Private Const CAT_CAPTURE_FORMAT_TIFF As Long = 1
Private Const CAT_CAPTURE_FORMAT_JPEG As Long = 2

' Excel constants for late binding.
Private Const XL_OPENXML_WORKBOOK As Long = 51
Private Const XL_CENTER As Long = -4108
Private Const XL_LEFT As Long = -4131
Private Const XL_TOP As Long = -4160
Private Const XL_CONTINUOUS As Long = 1
Private Const XL_THIN As Long = 2
Private Const MSO_TRUE As Long = -1
Private Const MSO_FALSE As Long = 0

' WIA image format IDs.
Private Const WIA_FORMAT_PNG As String = "{B96B3CAF-0728-11D3-9D7B-0000F81EF32E}"
Private Const WIA_FORMAT_JPEG As String = "{B96B3CAE-0728-11D3-9D7B-0000F81EF32E}"
Private Const WIA_FORMAT_BMP As String = "{B96B3CAB-0728-11D3-9D7B-0000F81EF32E}"

Private gFSO As Object
Private gShell As Object
Private gBomItems As Object
Private gAllProducts As Collection
Private gExportLog As Collection
Private gTotalInstances As Long
Private gOutputFolder As String
Private gImageFolder As String
Private gMainImagePath As String
Private gExcelPath As String
Private gRootProduct As Object
Private gActiveDoc As Object

Public Sub CATIA_VISUAL_BOM_EXPORTER()
    On Error GoTo FatalError

    Set gFSO = CreateObject("Scripting.FileSystemObject")
    Set gShell = CreateObject("WScript.Shell")
    Set gBomItems = CreateObject("Scripting.Dictionary")
    Set gAllProducts = New Collection
    Set gExportLog = New Collection
    gTotalInstances = 0
    Randomize

    If CATIA.Documents.Count = 0 Then
        MsgBox "Nema otvorenog CATIA dokumenta. Otvorite CATProduct sklop i pokrenite makro ponovo.", vbExclamation, "CATIA_VISUAL_BOM_EXPORTER"
        Exit Sub
    End If

    Set gActiveDoc = CATIA.ActiveDocument
    If Not IsActiveDocumentProduct(gActiveDoc) Then
        MsgBox "Aktivni dokument nije CATProduct/ProductDocument." & vbCrLf & _
               "Otvorite glavni CATProduct sklop i pokrenite makro ponovo.", vbExclamation, "CATIA_VISUAL_BOM_EXPORTER"
        Exit Sub
    End If

    Set gRootProduct = gActiveDoc.Product
    PrepareOutputFolders gActiveDoc, gRootProduct

    CATIA.StatusBar = "CATIA_VISUAL_BOM_EXPORTER: citam Product Tree..."
    BuildBomFromProductTree gRootProduct

    If gBomItems.Count = 0 Then
        MsgBox "Nije pronadjena nijedna BOM stavka za izvoz. Proverite EXPORT_PARTS / EXPORT_ASSEMBLIES / EXPORT_SELECTED_ONLY konfiguraciju.", _
               vbExclamation, "CATIA_VISUAL_BOM_EXPORTER"
        Exit Sub
    End If

    CATIA.StatusBar = "CATIA_VISUAL_BOM_EXPORTER: eksportujem slike..."
    ExportAllImages

    CATIA.StatusBar = "CATIA_VISUAL_BOM_EXPORTER: pravim Excel izvestaj..."
    CreateExcelReport

    RestoreWholeAssemblyView
    CATIA.StatusBar = "CATIA_VISUAL_BOM_EXPORTER: gotovo."

    MsgBox "Visual BOM export je zavrsen." & vbCrLf & vbCrLf & _
           "Folder:" & vbCrLf & gOutputFolder & vbCrLf & vbCrLf & _
           "Excel:" & vbCrLf & gExcelPath, vbInformation, "CATIA_VISUAL_BOM_EXPORTER"
    Exit Sub

FatalError:
    On Error Resume Next
    RestoreWholeAssemblyView
    CATIA.StatusBar = ""
    MsgBox "Makro je zaustavljen zbog greske:" & vbCrLf & _
           Err.Number & " - " & Err.Description, vbCritical, "CATIA_VISUAL_BOM_EXPORTER"
End Sub

Private Function IsActiveDocumentProduct(ByVal doc As Object) As Boolean
    On Error Resume Next
    Dim typeText As String
    Dim nameText As String

    typeText = TypeName(doc)
    nameText = CStr(doc.Name)

    If InStr(1, typeText, "ProductDocument", vbTextCompare) > 0 Then
        IsActiveDocumentProduct = True
    ElseIf LCase$(Right$(nameText, 11)) = ".catproduct" Then
        IsActiveDocumentProduct = True
    Else
        IsActiveDocumentProduct = False
    End If
    Err.Clear
End Function

Private Sub PrepareOutputFolders(ByVal doc As Object, ByVal rootProduct As Object)
    Dim baseFolder As String
    Dim rootName As String

    rootName = SafeFileName(FirstNonEmpty(GetProductPartNumber(rootProduct), rootProduct.Name, "CATProduct"))
    If rootName = "" Then rootName = "CATProduct"

    If OUTPUT_TO_DESKTOP Then
        baseFolder = gShell.SpecialFolders("Desktop")
    Else
        baseFolder = GetDocumentFolder(doc)
        If baseFolder = "" Then baseFolder = gShell.SpecialFolders("Desktop")
    End If

    gOutputFolder = JoinPath(baseFolder, rootName & "_VISUAL_BOM_EXPORT")
    gImageFolder = JoinPath(gOutputFolder, "IMAGES")
    gMainImagePath = JoinPath(gOutputFolder, "MAIN_ASSEMBLY." & LCase$(IMAGE_FORMAT))
    gExcelPath = JoinPath(gOutputFolder, "VISUAL_BOM_EXPORT.xlsx")

    EnsureFolder gOutputFolder
    EnsureFolder gImageFolder
End Sub

Private Function GetDocumentFolder(ByVal doc As Object) As String
    On Error Resume Next
    GetDocumentFolder = CStr(doc.Path)
    If Err.Number <> 0 Then
        Err.Clear
        GetDocumentFolder = ""
    End If
End Function

Private Sub BuildBomFromProductTree(ByVal rootProduct As Object)
    Dim selectedProducts As Collection
    Set selectedProducts = GetSelectedProducts()

    Dim rootPath As String
    rootPath = FirstNonEmpty(GetProductPartNumber(rootProduct), rootProduct.Name, "ROOT")

    Dim pathProducts As Collection
    Set pathProducts = New Collection
    pathProducts.Add rootProduct

    TraverseProductChildren rootProduct, "", rootPath, pathProducts, selectedProducts, False
End Sub

Private Sub TraverseProductChildren(ByVal parentProduct As Object, _
                                    ByVal parentAssemblyName As String, _
                                    ByVal parentTreePath As String, _
                                    ByVal parentPathProducts As Collection, _
                                    ByVal selectedProducts As Collection, _
                                    ByVal parentWasSelected As Boolean)
    On Error GoTo TraverseError

    Dim children As Object
    Set children = parentProduct.Products

    Dim i As Long
    For i = 1 To children.Count
        Dim child As Object
        Set child = children.Item(i)

        gAllProducts.Add child

        Dim childPartNumber As String
        Dim childLabel As String
        Dim childTreePath As String
        Dim childPathProducts As Collection
        Dim childSelected As Boolean

        childPartNumber = GetProductPartNumber(child)
        childLabel = FirstNonEmpty(childPartNumber, child.Name, "ITEM_" & CStr(gAllProducts.Count))
        childTreePath = parentTreePath & "\" & childLabel

        Set childPathProducts = CloneCollection(parentPathProducts)
        childPathProducts.Add child

        childSelected = parentWasSelected Or IsProductInSelection(child, selectedProducts)

        If ShouldExportProduct(child, childSelected) Then
            AddOrUpdateBomItem child, parentAssemblyName, childTreePath, childPathProducts
        End If

        If HasChildren(child) Then
            TraverseProductChildren child, childLabel, childTreePath, childPathProducts, selectedProducts, childSelected
        End If
    Next i
    Exit Sub

TraverseError:
    AddLog "", "WARNING", "Ne mogu potpuno da procitam decu sklopa '" & SafeText(parentProduct.Name) & "': " & Err.Description, ""
    Err.Clear
End Sub

Private Function GetSelectedProducts() As Collection
    Set GetSelectedProducts = New Collection
    If Not EXPORT_SELECTED_ONLY Then Exit Function

    On Error Resume Next
    Dim sel As Object
    Set sel = gActiveDoc.Selection
    If sel Is Nothing Then Exit Function

    Dim i As Long
    For i = 1 To sel.Count2
        Dim obj As Object
        Set obj = sel.Item2(i).Value
        If IsProductObject(obj) Then GetSelectedProducts.Add obj
    Next i
    Err.Clear
End Function

Private Function IsProductInSelection(ByVal prod As Object, ByVal selectedProducts As Collection) As Boolean
    If Not EXPORT_SELECTED_ONLY Then
        IsProductInSelection = True
        Exit Function
    End If

    Dim i As Long
    For i = 1 To selectedProducts.Count
        If selectedProducts.Item(i) Is prod Then
            IsProductInSelection = True
            Exit Function
        End If
    Next i
End Function

Private Function ShouldExportProduct(ByVal prod As Object, ByVal selectedOrChildOfSelected As Boolean) As Boolean
    If EXPORT_SELECTED_ONLY And Not selectedOrChildOfSelected Then Exit Function

    Dim t As String
    t = GetProductBomType(prod)

    If t = "Assembly" And EXPORT_ASSEMBLIES Then
        ShouldExportProduct = True
    ElseIf t = "Part" And EXPORT_PARTS Then
        ShouldExportProduct = True
    End If
End Function

Private Sub AddOrUpdateBomItem(ByVal prod As Object, _
                               ByVal parentAssemblyName As String, _
                               ByVal treePath As String, _
                               ByVal pathProducts As Collection)
    On Error GoTo AddError

    gTotalInstances = gTotalInstances + 1

    Dim pn As String
    Dim key As String
    Dim rec As Object

    pn = GetProductPartNumber(prod)
    If pn <> "" Then
        key = "PN|" & UCase$(Trim$(pn))
    Else
        key = "INSTANCE|" & UCase$(Trim$(treePath))
    End If

    If gBomItems.Exists(key) Then
        Set rec = gBomItems.Item(key)
        rec.Item("Quantity") = CLng(rec.Item("Quantity")) + 1

        If InStr(1, rec.Item("ParentAssembly"), parentAssemblyName, vbTextCompare) = 0 Then
            If rec.Item("ParentAssembly") <> "" And parentAssemblyName <> "" Then
                rec.Item("ParentAssembly") = rec.Item("ParentAssembly") & "; " & parentAssemblyName
            ElseIf parentAssemblyName <> "" Then
                rec.Item("ParentAssembly") = parentAssemblyName
            End If
        End If

        If InStr(1, rec.Item("TreePath"), treePath, vbTextCompare) = 0 Then
            rec.Item("TreePath") = rec.Item("TreePath") & vbLf & treePath
        End If

        If CStr(rec.Item("Note")) = "" Then
            rec.Item("Note") = "Grouped by Part Number; metadata and preview from first instance."
        End If
    Else
        Set rec = CreateObject("Scripting.Dictionary")
        rec.Add "No", CLng(gBomItems.Count + 1)
        rec.Add "Quantity", CLng(1)
        rec.Add "PartNumber", pn
        rec.Add "Revision", GetProductRevision(prod)
        rec.Add "Type", GetProductBomType(prod)
        rec.Add "Nomenclature", GetProductNomenclature(prod)
        rec.Add "Material", GetPropertyValue(prod, "Material", "Materijal")
        rec.Add "Dimension", GetPropertyValue(prod, "Dimension", "Dimenzija")
        rec.Add "Mass", GetProductMass(prod)
        rec.Add "Standard", GetPropertyValue(prod, "Standard")
        rec.Add "ParentAssembly", parentAssemblyName
        rec.Add "TreePath", treePath
        rec.Add "ImageFile", ""
        rec.Add "ImagePath", ""
        rec.Add "ExportStatus", "PENDING"
        rec.Add "Note", IIf(pn = "", "Part Number missing; exported as separate instance.", "")
        rec.Add "Key", key
        rec.Add "PathProducts", pathProducts
        rec.Add "ProductRef", prod
        gBomItems.Add key, rec
    End If
    Exit Sub

AddError:
    AddLog pn, "WARNING", "BOM stavka nije dodata: " & Err.Description, ""
    Err.Clear
End Sub

Private Sub ExportAllImages()
    On Error Resume Next
    TrySetCatiaWindowSize IMAGE_WIDTH, IMAGE_HEIGHT
    RestoreWholeAssemblyView
    ApplyIsoViewAndFit

    If CaptureCurrentViewer(gMainImagePath) Then
        AddLog GetProductPartNumber(gRootProduct), "OK", "Main assembly image exported.", gMainImagePath
    Else
        AddLog GetProductPartNumber(gRootProduct), "ERROR", "Main assembly image export failed.", gMainImagePath
    End If

    Dim key As Variant
    For Each key In gBomItems.Keys
        Dim rec As Object
        Set rec = gBomItems.Item(CStr(key))
        ExportImageForBomRecord rec
    Next key

    RestoreWholeAssemblyView
End Sub

Private Sub ExportImageForBomRecord(ByVal rec As Object)
    On Error GoTo ExportError

    Dim productRef As Object
    Dim pathProducts As Collection
    Dim imagePath As String
    Dim imageFile As String

    Set productRef = rec.Item("ProductRef")
    Set pathProducts = rec.Item("PathProducts")

    imageFile = BuildUniqueImageFileName(CStr(rec.Item("PartNumber")), CStr(rec.Item("Nomenclature")), CLng(rec.Item("No")))
    imagePath = JoinPath(gImageFolder, imageFile)

    HideAllComponents
    ShowProductPath pathProducts
    ShowProductSubtree productRef
    ApplyIsoViewAndFit

    If CaptureCurrentViewer(imagePath) Then
        imageFile = gFSO.GetFileName(imagePath)
        rec.Item("ImageFile") = imageFile
        rec.Item("ImagePath") = imagePath
        rec.Item("ExportStatus") = "OK"
        AddLog CStr(rec.Item("PartNumber")), "OK", "Image exported.", imagePath
    Else
        rec.Item("ImageFile") = imageFile
        rec.Item("ImagePath") = imagePath
        rec.Item("ExportStatus") = "ERROR"
        rec.Item("Note") = AppendNote(CStr(rec.Item("Note")), "Image export failed.")
        AddLog CStr(rec.Item("PartNumber")), "ERROR", "Image export failed.", imagePath
    End If

    Exit Sub

ExportError:
    rec.Item("ExportStatus") = "ERROR"
    rec.Item("Note") = AppendNote(CStr(rec.Item("Note")), "Image export error: " & Err.Description)
    AddLog CStr(rec.Item("PartNumber")), "ERROR", "Image export error: " & Err.Description, ""
    Err.Clear
End Sub

Private Function CaptureCurrentViewer(ByRef targetPath As String) As Boolean
    On Error GoTo CaptureFailed

    Dim viewer As Object
    Set viewer = CATIA.ActiveWindow.ActiveViewer
    viewer.Activate
    viewer.Update
    WaitSeconds 0.25

    Dim ext As String
    ext = LCase$(gFSO.GetExtensionName(targetPath))

    If ext = "png" Then
        Dim tempBmp As String
        tempBmp = JoinPath(gOutputFolder, "~catia_capture_temp_" & Format(Now, "yyyymmdd_hhnnss") & "_" & CStr(Int(Rnd() * 100000)) & ".bmp")
        viewer.CaptureToFile CAT_CAPTURE_FORMAT_BMP, tempBmp
        WaitSeconds 0.1

        If gFSO.FileExists(tempBmp) Then
            If ConvertImageWithWia(tempBmp, targetPath, WIA_FORMAT_PNG) Then
                On Error Resume Next
                gFSO.DeleteFile tempBmp, True
                On Error GoTo CaptureFailed
                CaptureCurrentViewer = gFSO.FileExists(targetPath)
                Exit Function
            Else
                Dim jpgFallback As String
                jpgFallback = Left$(targetPath, Len(targetPath) - Len(ext)) & "jpg"
                viewer.CaptureToFile CAT_CAPTURE_FORMAT_JPEG, jpgFallback
                If gFSO.FileExists(jpgFallback) Then
                    AddLog "", "WARNING", "PNG conversion through WIA failed; JPEG fallback created.", jpgFallback
                    CaptureCurrentViewer = True
                    targetPath = jpgFallback
                    On Error Resume Next
                    gFSO.DeleteFile tempBmp, True
                    Exit Function
                End If
            End If
        End If
    ElseIf ext = "jpg" Or ext = "jpeg" Then
        viewer.CaptureToFile CAT_CAPTURE_FORMAT_JPEG, targetPath
    ElseIf ext = "tif" Or ext = "tiff" Then
        viewer.CaptureToFile CAT_CAPTURE_FORMAT_TIFF, targetPath
    Else
        viewer.CaptureToFile CAT_CAPTURE_FORMAT_BMP, targetPath
    End If

    CaptureCurrentViewer = gFSO.FileExists(targetPath)
    Exit Function

CaptureFailed:
    CaptureCurrentViewer = False
    Err.Clear
End Function

Private Function ConvertImageWithWia(ByVal sourcePath As String, ByVal targetPath As String, ByVal formatId As String) As Boolean
    On Error GoTo WiaFailed

    If gFSO.FileExists(targetPath) Then gFSO.DeleteFile targetPath, True

    Dim img As Object
    Dim proc As Object
    Dim converted As Object

    Set img = CreateObject("WIA.ImageFile")
    img.LoadFile sourcePath

    Set proc = CreateObject("WIA.ImageProcess")
    proc.Filters.Add proc.FilterInfos("Convert").FilterID
    proc.Filters(1).Properties("FormatID").Value = formatId

    Set converted = proc.Apply(img)
    converted.SaveFile targetPath

    ConvertImageWithWia = gFSO.FileExists(targetPath)
    Exit Function

WiaFailed:
    ConvertImageWithWia = False
    Err.Clear
End Function

Private Sub HideAllComponents()
    SetVisibilityForCollection gAllProducts, False
End Sub

Private Sub ShowProductPath(ByVal pathProducts As Collection)
    SetVisibilityForCollection pathProducts, True
End Sub

Private Sub ShowProductSubtree(ByVal productRoot As Object)
    On Error Resume Next

    Dim subtree As Collection
    Set subtree = New Collection
    CollectSubtreeProducts productRoot, subtree
    SetVisibilityForCollection subtree, True
    Err.Clear
End Sub

Private Sub CollectSubtreeProducts(ByVal productRoot As Object, ByVal result As Collection)
    On Error Resume Next

    result.Add productRoot

    Dim children As Object
    Set children = productRoot.Products
    If Err.Number <> 0 Or children Is Nothing Then
        Err.Clear
        Exit Sub
    End If

    Dim i As Long
    For i = 1 To children.Count
        CollectSubtreeProducts children.Item(i), result
    Next i
    Err.Clear
End Sub

Private Sub RestoreWholeAssemblyView()
    On Error Resume Next
    SetVisibilityForCollection gAllProducts, True
    ApplyIsoViewAndFit
    gActiveDoc.Selection.Clear
    Err.Clear
End Sub

Private Sub SetVisibilityForCollection(ByVal products As Collection, ByVal showIt As Boolean)
    On Error Resume Next

    Dim sel As Object
    Set sel = gActiveDoc.Selection
    sel.Clear

    Dim i As Long
    For i = 1 To products.Count
        sel.Add products.Item(i)
        If (i Mod 200) = 0 Then
            If showIt Then
                sel.VisProperties.SetShow CAT_VIS_PROPERTY_SHOW
            Else
                sel.VisProperties.SetShow CAT_VIS_PROPERTY_NO_SHOW
            End If
            sel.Clear
        End If
    Next i

    If sel.Count2 > 0 Then
        If showIt Then
            sel.VisProperties.SetShow CAT_VIS_PROPERTY_SHOW
        Else
            sel.VisProperties.SetShow CAT_VIS_PROPERTY_NO_SHOW
        End If
    End If

    sel.Clear
    CATIA.RefreshDisplay = True
    WaitSeconds 0.1
    Err.Clear
End Sub

Private Sub ApplyIsoViewAndFit()
    On Error Resume Next

    Dim viewer As Object
    Set viewer = CATIA.ActiveWindow.ActiveViewer
    viewer.Activate

    Dim vp As Object
    Set vp = viewer.Viewpoint3D

    Dim sight(2) As Double
    Dim up(2) As Double
    sight(0) = 1#
    sight(1) = -1#
    sight(2) = 1#
    up(0) = -0.4082482905
    up(1) = 0.4082482905
    up(2) = 0.8164965809

    vp.PutSightDirection sight
    vp.PutUpDirection up
    vp.ProjectionMode = 0

    viewer.Update
    viewer.Reframe
    viewer.Update
    WaitSeconds 0.2
    Err.Clear
End Sub

Private Sub TrySetCatiaWindowSize(ByVal widthPx As Long, ByVal heightPx As Long)
    On Error Resume Next
    CATIA.ActiveWindow.Width = widthPx
    CATIA.ActiveWindow.Height = heightPx
    CATIA.ActiveWindow.ActiveViewer.Update
    Err.Clear
End Sub

Private Sub CreateExcelReport()
    On Error GoTo ExcelFatal

    Dim xl As Object
    Dim wb As Object
    Dim wsSummary As Object
    Dim wsBom As Object
    Dim wsLog As Object

    Set xl = CreateObject("Excel.Application")
    If xl Is Nothing Then
        MsgBox "Microsoft Excel nije dostupan preko COM automation.", vbCritical, "CATIA_VISUAL_BOM_EXPORTER"
        Exit Sub
    End If

    xl.Visible = False
    xl.DisplayAlerts = False

    Set wb = xl.Workbooks.Add
    Do While wb.Worksheets.Count < 3
        wb.Worksheets.Add After:=wb.Worksheets(wb.Worksheets.Count)
    Loop

    Set wsSummary = wb.Worksheets(1)
    Set wsBom = wb.Worksheets(2)
    Set wsLog = wb.Worksheets(3)

    wsSummary.Name = "SUMMARY"
    wsBom.Name = "BOM"
    wsLog.Name = "EXPORT_LOG"

    FillSummarySheet wsSummary
    FillBomSheet wsBom
    FillLogSheet wsLog

    xl.DisplayAlerts = False
    If gFSO.FileExists(gExcelPath) Then gFSO.DeleteFile gExcelPath, True
    wb.SaveAs gExcelPath, XL_OPENXML_WORKBOOK
    xl.Visible = True
    xl.DisplayAlerts = True
    Exit Sub

ExcelFatal:
    On Error Resume Next
    If Not xl Is Nothing Then
        xl.DisplayAlerts = True
        xl.Visible = True
    End If
    MsgBox "Excel izvestaj nije napravljen:" & vbCrLf & _
           Err.Number & " - " & Err.Description, vbCritical, "CATIA_VISUAL_BOM_EXPORTER"
End Sub

Private Sub FillSummarySheet(ByVal ws As Object)
    On Error Resume Next

    ws.Cells.Clear
    ws.Range("A1").Value = "CATIA VISUAL BOM EXPORTER"
    ws.Range("A3").Value = "Main Assembly Part Number"
    ws.Range("B3").Value = GetProductPartNumber(gRootProduct)
    ws.Range("A4").Value = "Main Assembly Nomenclature"
    ws.Range("B4").Value = GetProductNomenclature(gRootProduct)
    ws.Range("A5").Value = "Export Date/Time"
    ws.Range("B5").Value = Now
    ws.Range("A6").Value = "Distinct BOM Items"
    ws.Range("B6").Value = gBomItems.Count
    ws.Range("A7").Value = "Total Instances"
    ws.Range("B7").Value = gTotalInstances
    ws.Range("A8").Value = "Output Folder"
    ws.Range("B8").Value = gOutputFolder
    ws.Range("A10").Value = "Main Assembly Preview"

    ws.Range("A1:B1").Merge
    ws.Range("A1").Font.Bold = True
    ws.Range("A1").Font.Size = 16
    ws.Range("A3:A10").Font.Bold = True
    ws.Columns("A").ColumnWidth = 28
    ws.Columns("B").ColumnWidth = 90
    ws.Rows("11:28").RowHeight = 22

    If INSERT_IMAGES_IN_EXCEL And gFSO.FileExists(gMainImagePath) Then
        InsertPictureIntoRange ws, gMainImagePath, "A11:D28"
    End If

    ApplyUsedRangeBorders ws
End Sub

Private Sub FillBomSheet(ByVal ws As Object)
    On Error Resume Next

    ws.Cells.Clear

    Dim headers As Variant
    headers = Array("No.", "Quantity", "Part Number", "Revision", "Type", "Nomenclature", _
                    "Material", "Dimension", "Mass", "Standard", "Parent Assembly", _
                    "Tree Path", "Image File", "Preview Image", "Export Status", "Note")

    Dim c As Long
    For c = LBound(headers) To UBound(headers)
        ws.Cells(1, c + 1).Value = headers(c)
    Next c

    Dim rowIndex As Long
    rowIndex = 2

    Dim key As Variant
    For Each key In gBomItems.Keys
        Dim rec As Object
        Set rec = gBomItems.Item(CStr(key))

        ws.Cells(rowIndex, 1).Value = rec.Item("No")
        ws.Cells(rowIndex, 2).Value = rec.Item("Quantity")
        ws.Cells(rowIndex, 3).Value = rec.Item("PartNumber")
        ws.Cells(rowIndex, 4).Value = rec.Item("Revision")
        ws.Cells(rowIndex, 5).Value = rec.Item("Type")
        ws.Cells(rowIndex, 6).Value = rec.Item("Nomenclature")
        ws.Cells(rowIndex, 7).Value = rec.Item("Material")
        ws.Cells(rowIndex, 8).Value = rec.Item("Dimension")
        ws.Cells(rowIndex, 9).Value = rec.Item("Mass")
        ws.Cells(rowIndex, 10).Value = rec.Item("Standard")
        ws.Cells(rowIndex, 11).Value = rec.Item("ParentAssembly")
        ws.Cells(rowIndex, 12).Value = rec.Item("TreePath")
        ws.Cells(rowIndex, 13).Value = rec.Item("ImageFile")
        ws.Cells(rowIndex, 15).Value = rec.Item("ExportStatus")
        ws.Cells(rowIndex, 16).Value = rec.Item("Note")

        ws.Rows(rowIndex).RowHeight = IIf(INSERT_IMAGES_IN_EXCEL, 95, 28)

        If INSERT_IMAGES_IN_EXCEL And CStr(rec.Item("ImagePath")) <> "" And gFSO.FileExists(CStr(rec.Item("ImagePath"))) Then
            InsertPictureIntoCell ws, CStr(rec.Item("ImagePath")), ws.Cells(rowIndex, 14)
        End If

        rowIndex = rowIndex + 1
    Next key

    FormatBomSheet ws, rowIndex - 1
End Sub

Private Sub FillLogSheet(ByVal ws As Object)
    On Error Resume Next

    ws.Cells.Clear
    ws.Cells(1, 1).Value = "No."
    ws.Cells(1, 2).Value = "Date/Time"
    ws.Cells(1, 3).Value = "Part Number"
    ws.Cells(1, 4).Value = "Status"
    ws.Cells(1, 5).Value = "Message"
    ws.Cells(1, 6).Value = "Image Path"

    Dim i As Long
    For i = 1 To gExportLog.Count
        Dim rec As Object
        Set rec = gExportLog.Item(i)
        ws.Cells(i + 1, 1).Value = i
        ws.Cells(i + 1, 2).Value = rec.Item("DateTime")
        ws.Cells(i + 1, 3).Value = rec.Item("PartNumber")
        ws.Cells(i + 1, 4).Value = rec.Item("Status")
        ws.Cells(i + 1, 5).Value = rec.Item("Message")
        ws.Cells(i + 1, 6).Value = rec.Item("ImagePath")
    Next i

    ws.Rows(1).Font.Bold = True
    ws.Rows(1).Interior.Color = RGB(220, 230, 241)
    ws.Columns("A").ColumnWidth = 8
    ws.Columns("B").ColumnWidth = 22
    ws.Columns("C").ColumnWidth = 28
    ws.Columns("D").ColumnWidth = 14
    ws.Columns("E").ColumnWidth = 70
    ws.Columns("F").ColumnWidth = 90
    ws.Range("A1:F1").AutoFilter
    ws.Columns("A:F").VerticalAlignment = XL_TOP
    ApplyUsedRangeBorders ws
End Sub

Private Sub FormatBomSheet(ByVal ws As Object, ByVal lastRow As Long)
    On Error Resume Next

    ws.Rows(1).Font.Bold = True
    ws.Rows(1).Interior.Color = RGB(220, 230, 241)
    ws.Rows(1).HorizontalAlignment = XL_CENTER

    ws.Columns("A").ColumnWidth = 7
    ws.Columns("B").ColumnWidth = 10
    ws.Columns("C").ColumnWidth = 28
    ws.Columns("D").ColumnWidth = 14
    ws.Columns("E").ColumnWidth = 12
    ws.Columns("F").ColumnWidth = 32
    ws.Columns("G").ColumnWidth = 20
    ws.Columns("H").ColumnWidth = 24
    ws.Columns("I").ColumnWidth = 16
    ws.Columns("J").ColumnWidth = 18
    ws.Columns("K").ColumnWidth = 28
    ws.Columns("L").ColumnWidth = 65
    ws.Columns("M").ColumnWidth = 32
    ws.Columns("N").ColumnWidth = 24
    ws.Columns("O").ColumnWidth = 16
    ws.Columns("P").ColumnWidth = 42

    If lastRow >= 2 Then
        ws.Range("A1:P" & CStr(lastRow)).WrapText = True
        ws.Range("A1:P" & CStr(lastRow)).VerticalAlignment = XL_TOP
        ws.Range("A1:P" & CStr(lastRow)).Borders.LineStyle = XL_CONTINUOUS
        ws.Range("A1:P" & CStr(lastRow)).Borders.Weight = XL_THIN
        ws.Range("A1:P1").AutoFilter
    End If

    ws.Activate
    ws.Range("A2").Select
    ActiveWindowFreezePanesSafe
End Sub

Private Sub ActiveWindowFreezePanesSafe()
    On Error Resume Next
    Dim xl As Object
    Set xl = GetObject(, "Excel.Application")
    If Not xl Is Nothing Then
        xl.ActiveWindow.FreezePanes = True
    End If
End Sub

Private Sub InsertPictureIntoCell(ByVal ws As Object, ByVal imagePath As String, ByVal cell As Object)
    On Error GoTo InsertFailed

    Dim shp As Object
    Dim margin As Double
    Dim maxW As Double
    Dim maxH As Double

    margin = 4
    maxW = cell.Width - (2 * margin)
    maxH = cell.Height - (2 * margin)
    If maxW < 10 Or maxH < 10 Then Exit Sub

    Set shp = ws.Shapes.AddPicture(imagePath, MSO_FALSE, MSO_TRUE, cell.Left + margin, cell.Top + margin, maxW, maxH)
    shp.LockAspectRatio = MSO_TRUE

    If shp.Width / maxW > shp.Height / maxH Then
        shp.Width = maxW
    Else
        shp.Height = maxH
    End If

    shp.Left = cell.Left + (cell.Width - shp.Width) / 2
    shp.Top = cell.Top + (cell.Height - shp.Height) / 2
    Exit Sub

InsertFailed:
    AddLog "", "WARNING", "Excel nije uspeo da ubaci sliku: " & imagePath & " | " & Err.Description, imagePath
    Err.Clear
End Sub

Private Sub InsertPictureIntoRange(ByVal ws As Object, ByVal imagePath As String, ByVal rangeAddress As String)
    On Error GoTo InsertFailed

    Dim rg As Object
    Set rg = ws.Range(rangeAddress)

    Dim shp As Object
    Set shp = ws.Shapes.AddPicture(imagePath, MSO_FALSE, MSO_TRUE, rg.Left + 4, rg.Top + 4, rg.Width - 8, rg.Height - 8)
    shp.LockAspectRatio = MSO_TRUE

    If shp.Width > rg.Width - 8 Then shp.Width = rg.Width - 8
    If shp.Height > rg.Height - 8 Then shp.Height = rg.Height - 8

    shp.Left = rg.Left + (rg.Width - shp.Width) / 2
    shp.Top = rg.Top + (rg.Height - shp.Height) / 2
    Exit Sub

InsertFailed:
    AddLog "", "WARNING", "Excel nije uspeo da ubaci summary sliku: " & Err.Description, imagePath
    Err.Clear
End Sub

Private Sub ApplyUsedRangeBorders(ByVal ws As Object)
    On Error Resume Next
    ws.UsedRange.Borders.LineStyle = XL_CONTINUOUS
    ws.UsedRange.Borders.Weight = XL_THIN
End Sub

Private Sub AddLog(ByVal partNumber As String, ByVal statusText As String, ByVal messageText As String, ByVal imagePath As String)
    On Error Resume Next
    Dim rec As Object
    Set rec = CreateObject("Scripting.Dictionary")
    rec.Add "DateTime", Now
    rec.Add "PartNumber", partNumber
    rec.Add "Status", statusText
    rec.Add "Message", messageText
    rec.Add "ImagePath", imagePath
    gExportLog.Add rec
End Sub

Private Function GetProductPartNumber(ByVal prod As Object) As String
    On Error Resume Next
    GetProductPartNumber = Trim$(CStr(prod.PartNumber))
    If GetProductPartNumber = "" Then GetProductPartNumber = GetPropertyValue(prod, "Part Number", "PartNumber", "PN")
    Err.Clear
End Function

Private Function GetProductRevision(ByVal prod As Object) As String
    On Error Resume Next
    GetProductRevision = Trim$(CStr(prod.Revision))
    If GetProductRevision = "" Then GetProductRevision = GetPropertyValue(prod, "Revision", "Revizija", "Rev")
    Err.Clear
End Function

Private Function GetProductNomenclature(ByVal prod As Object) As String
    On Error Resume Next
    GetProductNomenclature = Trim$(CStr(prod.Nomenclature))
    If GetProductNomenclature = "" Then GetProductNomenclature = GetPropertyValue(prod, "Nomenclature", "Nomenklatura", "Description", "Opis")
    Err.Clear
End Function

Private Function GetProductMass(ByVal prod As Object) As String
    On Error Resume Next

    Dim massFromProperty As String
    massFromProperty = GetPropertyValue(prod, "Mass", "Masa")
    If massFromProperty <> "" Then
        GetProductMass = massFromProperty
        Exit Function
    End If

    Dim analyzeObj As Object
    Dim m As Double
    Set analyzeObj = prod.Analyze
    m = CDbl(analyzeObj.Mass)
    If Err.Number = 0 And m <> 0 Then
        GetProductMass = Format$(m, "0.###")
    Else
        Err.Clear
        Dim refProd As Object
        Set refProd = prod.ReferenceProduct
        If Not refProd Is Nothing Then
            Set analyzeObj = refProd.Analyze
            m = CDbl(analyzeObj.Mass)
            If Err.Number = 0 And m <> 0 Then GetProductMass = Format$(m, "0.###")
        End If
    End If
    Err.Clear
End Function

Public Function GetPropertyValue(ByVal prod As Object, ParamArray propNames() As Variant) As String
    On Error Resume Next

    GetPropertyValue = TryGetPropertyValueFromProduct(prod, propNames)
    If GetPropertyValue <> "" Then Exit Function

    Dim refProd As Object
    Set refProd = prod.ReferenceProduct
    If Not refProd Is Nothing Then
        GetPropertyValue = TryGetPropertyValueFromProduct(refProd, propNames)
    End If
    Err.Clear
End Function

Private Function TryGetPropertyValueFromProduct(ByVal prod As Object, ByVal propNames As Variant) As String
    On Error Resume Next

    Dim v As String
    Dim props As Object
    Dim params As Object
    Dim nm As Variant

    Set props = prod.UserRefProperties
    If Not props Is Nothing Then
        For Each nm In propNames
            v = TryGetParameterValueByName(props, CStr(nm))
            If v <> "" Then
                TryGetPropertyValueFromProduct = v
                Exit Function
            End If
        Next nm
    End If

    Set params = prod.Parameters
    If Not params Is Nothing Then
        For Each nm In propNames
            v = TryGetParameterValueByName(params, CStr(nm))
            If v <> "" Then
                TryGetPropertyValueFromProduct = v
                Exit Function
            End If
        Next nm
    End If

    Err.Clear
End Function

Private Function TryGetParameterValueByName(ByVal params As Object, ByVal wantedName As String) As String
    On Error Resume Next

    Dim p As Object
    Dim v As String

    Set p = params.Item(wantedName)
    If Err.Number = 0 And Not p Is Nothing Then
        v = ParameterValueAsText(p)
        If v <> "" Then
            TryGetParameterValueByName = v
            Exit Function
        End If
    End If
    Err.Clear

    Dim i As Long
    For i = 1 To params.Count
        Set p = params.Item(i)
        If Err.Number = 0 And Not p Is Nothing Then
            If ParameterNameMatches(CStr(p.Name), wantedName) Then
                v = ParameterValueAsText(p)
                If v <> "" Then
                    TryGetParameterValueByName = v
                    Exit Function
                End If
            End If
        End If
        Err.Clear
    Next i
End Function

Private Function ParameterNameMatches(ByVal actualName As String, ByVal wantedName As String) As Boolean
    Dim a As String
    Dim w As String
    a = LCase$(Trim$(actualName))
    w = LCase$(Trim$(wantedName))

    ParameterNameMatches = (a = w Or Right$(a, Len(w) + 1) = "\" & w Or Right$(a, Len(w) + 1) = "/" & w)
End Function

Private Function ParameterValueAsText(ByVal p As Object) As String
    On Error Resume Next

    ParameterValueAsText = Trim$(CStr(p.ValueAsString))
    If ParameterValueAsText <> "" Then Exit Function

    Err.Clear
    ParameterValueAsText = Trim$(CStr(p.Value))
    If ParameterValueAsText <> "" Then Exit Function

    Err.Clear
End Function

Private Function GetProductBomType(ByVal prod As Object) As String
    If HasChildren(prod) Then
        GetProductBomType = "Assembly"
    Else
        GetProductBomType = "Part"
    End If
End Function

Private Function HasChildren(ByVal prod As Object) As Boolean
    On Error Resume Next
    Dim children As Object
    Set children = prod.Products
    HasChildren = (Err.Number = 0 And Not children Is Nothing And children.Count > 0)
    Err.Clear
End Function

Private Function IsProductObject(ByVal obj As Object) As Boolean
    On Error Resume Next
    Dim s As String
    s = CStr(obj.PartNumber)
    IsProductObject = (Err.Number = 0)
    Err.Clear
End Function

Private Function BuildUniqueImageFileName(ByVal partNumber As String, ByVal nomenclature As String, ByVal itemNo As Long) As String
    Dim baseName As String
    Dim ext As String
    Dim candidate As String
    Dim n As Long

    ext = LCase$(IMAGE_FORMAT)
    If ext = "" Then ext = "jpg"

    baseName = SafeFileName(Trim$(partNumber & "_" & nomenclature))
    If baseName = "" Or baseName = "_" Then baseName = "ITEM_" & Format$(itemNo, "0000")
    If Len(baseName) > 140 Then baseName = Left$(baseName, 140)

    candidate = baseName & "." & ext
    n = 1
    Do While gFSO.FileExists(JoinPath(gImageFolder, candidate))
        candidate = baseName & "_" & Format$(n, "000") & "." & ext
        n = n + 1
    Loop

    BuildUniqueImageFileName = candidate
End Function

Private Function SafeFileName(ByVal valueText As String) As String
    Dim s As String
    Dim badChars As Variant
    Dim ch As Variant

    s = Trim$(valueText)
    badChars = Array("\", "/", ":", "*", "?", """", "<", ">", "|", vbTab, vbCr, vbLf)
    For Each ch In badChars
        s = Replace(s, CStr(ch), "_")
    Next ch

    Do While InStr(s, "__") > 0
        s = Replace(s, "__", "_")
    Loop

    If Len(s) > 180 Then s = Left$(s, 180)
    SafeFileName = Trim$(s)
End Function

Private Function SafeText(ByVal valueText As String) As String
    SafeText = Replace(Replace(Trim$(valueText), vbCr, " "), vbLf, " ")
End Function

Private Function FirstNonEmpty(ParamArray values() As Variant) As String
    Dim v As Variant
    For Each v In values
        If Trim$(CStr(v)) <> "" Then
            FirstNonEmpty = Trim$(CStr(v))
            Exit Function
        End If
    Next v
End Function

Private Function AppendNote(ByVal oldNote As String, ByVal addNote As String) As String
    If Trim$(oldNote) = "" Then
        AppendNote = addNote
    Else
        AppendNote = oldNote & " " & addNote
    End If
End Function

Private Function CloneCollection(ByVal source As Collection) As Collection
    Dim result As Collection
    Set result = New Collection

    Dim i As Long
    For i = 1 To source.Count
        result.Add source.Item(i)
    Next i

    Set CloneCollection = result
End Function

Private Sub EnsureFolder(ByVal folderPath As String)
    If Not gFSO.FolderExists(folderPath) Then gFSO.CreateFolder folderPath
End Sub

Private Function JoinPath(ByVal folderPath As String, ByVal childName As String) As String
    If Right$(folderPath, 1) = "\" Then
        JoinPath = folderPath & childName
    Else
        JoinPath = folderPath & "\" & childName
    End If
End Function

Private Sub WaitSeconds(ByVal secondsToWait As Double)
    Dim startTime As Single
    Dim currentTime As Single

    startTime = Timer
    Do
        DoEvents
        currentTime = Timer
        If currentTime < startTime Then currentTime = currentTime + 86400!
    Loop While (currentTime - startTime) < CSng(secondsToWait)
End Sub
