Option Explicit

' ================================================================
' CATIA_VISUAL_BOM_EXPORTER
' CATIA V5 VBA macro for Product Tree / Visual BOM export to Excel.
' Paste this whole module into CATIA V5 VBA editor and run:
'     CATIA_VISUAL_BOM_EXPORTER
' ================================================================

' ---------------------- CONFIGURATION ---------------------------
Private Const IMAGE_FORMAT As String = "png"
Private Const FAST_SNIP_MODE As Boolean = True
Private Const FAST_IMAGE_FORMAT As String = "jpg"
Private Const FAST_ZOOM_IN_STEPS As Long = 0
Private Const FAST_CAPTURE_DELAY_SECONDS As Double = 0.05
' Veci FAST_CENTER_CROP_PERCENT znaci manje crop-a i vise prostora oko dela.
' Manji FAST_CENTER_CROP_PERCENT znaci jaci crop i blizi prikaz dela.
Private Const FAST_CENTER_CROP_PERCENT As Double = 0.9
Private Const MAX_SECONDS_PER_IMAGE As Double = 2
Private Const EXPORT_PARTS As Boolean = True
Private Const EXPORT_ASSEMBLIES As Boolean = True
Private Const EXPORT_SELECTED_ONLY As Boolean = False
Private Const USE_NICE_IMAGE_VIEW As Boolean = True
Private Const USE_SHADED_WITH_EDGES As Boolean = True
Private Const USE_WHITE_BACKGROUND As Boolean = True
Private Const USE_PARALLEL_PROJECTION As Boolean = True
Private Const IMAGE_CAPTURE_DELAY_SECONDS As Double = 0.35
Private Const IMAGE_FIT_REPEAT_COUNT As Long = 2
Private Const IMAGE_EXTRA_ZOOM_OUT_STEPS As Long = 0
Private Const ENABLE_IMAGE_CROP As Boolean = True
Private Const AUTO_CROP_WHITE_BACKGROUND As Boolean = True
Private Const WHITE_THRESHOLD As Long = 245
Private Const CROP_PADDING_PERCENT As Double = 0.04
Private Const FALLBACK_FIXED_CROP_PERCENT As Double = 0.08
Private Const USE_CATIA_DEFINED_BOM_COLUMNS As Boolean = True
Private Const BOM_COLUMNS As String = "Item|Part Number|Thumbnail|Keywords|QTY|Material|Dimenzija|Mass|Standard|Component Type|REV|Dim-MM|Description|Comments"
Private Const THUMBNAIL_WIDTH As Long = 160
Private Const THUMBNAIL_HEIGHT As Long = 120
Private Const SAVE_EVERY_N_ITEMS As Long = 10
Private Const SKIP_EXISTING_IMAGES As Boolean = True
Private Const START_INDEX As Long = 1
Private Const END_INDEX As Long = 0
Private Const EXPORT_IMAGES As Boolean = True
Private Const MAX_ITEMS_TO_EXPORT As Long = 20
Private Const SKIP_ASSEMBLIES As Boolean = True
Private Const IMAGE_EXPORT_TIMEOUT_SECONDS As Double = 10
Private Const IMAGE_WIDTH As Long = 1000
Private Const IMAGE_HEIGHT As Long = 750
Private Const INSERT_IMAGES_IN_EXCEL As Boolean = True
Private Const OUTPUT_TO_DESKTOP As Boolean = True

' CATIA VisProperties show constants.
Private Const CAT_VIS_PROPERTY_SHOW As Long = 0
Private Const CAT_VIS_PROPERTY_NO_SHOW As Long = 1

' CATIA capture formats. CATIA V5 Automation reliably supports BMP/JPEG/TIFF.
' PNG is generated by capturing BMP first and converting it through Windows WIA.
Private Const CAT_CAPTURE_FORMAT_BMP As Long = 0
Private Const CAT_CAPTURE_FORMAT_TIFF As Long = 1
Private Const CAT_CAPTURE_FORMAT_JPEG As Long = 2

' CATIA rendering/projection constants used late-bound from VBA.
Private Const CAT_RENDER_SHADING As Long = 0
Private Const CAT_RENDER_SHADING_WITH_EDGES As Long = 1
Private Const CAT_PROJECTION_CYLINDRIC As Long = 0
Private Const CAT_FILE_TYPE_TXT As Long = 0
Private Const CAT_FILE_TYPE_HTML As Long = 2

' Excel constants for late binding.
Private Const XL_OPENXML_WORKBOOK As Long = 51
Private Const XL_CENTER As Long = -4108
Private Const XL_LEFT As Long = -4131
Private Const XL_TOP As Long = -4160
Private Const XL_CONTINUOUS As Long = 1
Private Const XL_THIN As Long = 2
Private Const MSO_TRUE As Long = -1
Private Const MSO_FALSE As Long = 0

' WIA image format IDs.
Private Const WIA_FORMAT_PNG As String = "{B96B3CAF-0728-11D3-9D7B-0000F81EF32E}"
Private Const WIA_FORMAT_JPEG As String = "{B96B3CAE-0728-11D3-9D7B-0000F81EF32E}"
Private Const WIA_FORMAT_BMP As String = "{B96B3CAB-0728-11D3-9D7B-0000F81EF32E}"

Private gFSO As Object
Private gShell As Object
Private gBomItems As Object
Private gAllProducts As Collection
Private gExportLog As Collection
Private gTotalInstances As Long
Private gOutputFolder As String
Private gImageFolder As String
Private gMainImagePath As String
Private gExcelPath As String
Private gRootProduct As Object
Private gActiveDoc As Object
Private gBomHeaders As Collection
Private gThumbnailColumnIndex As Long
Private gImagePathColumnIndex As Long
Private gExportStatusColumnIndex As Long
Private gCatiaBomColumnsSource As String

Public Sub CATIA_VISUAL_BOM_EXPORTER()
    On Error GoTo FatalError

    Set gFSO = CreateObject("Scripting.FileSystemObject")
    Set gShell = CreateObject("WScript.Shell")
    Set gBomItems = CreateObject("Scripting.Dictionary")
    Set gAllProducts = New Collection
    Set gExportLog = New Collection
    Set gBomHeaders = New Collection
    gThumbnailColumnIndex = 0
    gImagePathColumnIndex = 0
    gExportStatusColumnIndex = 0
    gCatiaBomColumnsSource = ""
    gTotalInstances = 0
    Randomize

    If CATIA.Documents.Count = 0 Then
        MsgBox "Nema otvorenog CATIA dokumenta. Otvorite CATProduct sklop i pokrenite makro ponovo.", vbExclamation, "CATIA_VISUAL_BOM_EXPORTER"
        Exit Sub
    End If

    Set gActiveDoc = CATIA.ActiveDocument
    If Not IsActiveDocumentProduct(gActiveDoc) Then
        MsgBox "Aktivni dokument nije CATProduct/ProductDocument." & vbCrLf & _
               "Otvorite glavni CATProduct sklop i pokrenite makro ponovo.", vbExclamation, "CATIA_VISUAL_BOM_EXPORTER"
        Exit Sub
    End If

    Set gRootProduct = gActiveDoc.Product
    PrepareOutputFolders gActiveDoc, gRootProduct
    InitializeBomHeaders

    CATIA.StatusBar = "CATIA_VISUAL_BOM_EXPORTER: citam Product Tree..."
    BuildBomFromProductTree gRootProduct

    If gBomItems.Count = 0 Then
        MsgBox "Nije pronadjena nijedna BOM stavka za izvoz. Proverite EXPORT_PARTS / EXPORT_ASSEMBLIES / EXPORT_SELECTED_ONLY konfiguraciju.", _
               vbExclamation, "CATIA_VISUAL_BOM_EXPORTER"
        Exit Sub
    End If

    CATIA.StatusBar = "CATIA_VISUAL_BOM_EXPORTER: eksportujem slike..."
    ExportAllImages

    CATIA.StatusBar = "CATIA_VISUAL_BOM_EXPORTER: pravim Excel izvestaj..."
    CreateExcelReport

    SafeRestoreCatiaSession
    CATIA.StatusBar = "CATIA_VISUAL_BOM_EXPORTER: gotovo."

    MsgBox "Visual BOM export je zavrsen." & vbCrLf & vbCrLf & _
           "Folder:" & vbCrLf & gOutputFolder & vbCrLf & vbCrLf & _
           "Excel:" & vbCrLf & gExcelPath, vbInformation, "CATIA_VISUAL_BOM_EXPORTER"
    Exit Sub

FatalError:
    On Error Resume Next
    SafeRestoreCatiaSession
    MsgBox "Makro je zaustavljen zbog greske:" & vbCrLf & _
           Err.Number & " - " & Err.Description, vbCritical, "CATIA_VISUAL_BOM_EXPORTER"
End Sub

Private Function IsActiveDocumentProduct(ByVal doc As Object) As Boolean
    On Error Resume Next
    Dim typeText As String
    Dim nameText As String

    typeText = TypeName(doc)
    nameText = CStr(doc.Name)

    If InStr(1, typeText, "ProductDocument", vbTextCompare) > 0 Then
        IsActiveDocumentProduct = True
    ElseIf LCase$(Right$(nameText, 11)) = ".catproduct" Then
        IsActiveDocumentProduct = True
    Else
        IsActiveDocumentProduct = False
    End If
    Err.Clear
End Function

Private Sub PrepareOutputFolders(ByVal doc As Object, ByVal rootProduct As Object)
    Dim baseFolder As String
    Dim rootName As String

    rootName = SafeFileName(FirstNonEmpty(GetProductPartNumber(rootProduct), rootProduct.Name, "CATProduct"))
    If rootName = "" Then rootName = "CATProduct"

    If OUTPUT_TO_DESKTOP Then
        baseFolder = gShell.SpecialFolders("Desktop")
    Else
        baseFolder = GetDocumentFolder(doc)
        If baseFolder = "" Then baseFolder = gShell.SpecialFolders("Desktop")
    End If

    gOutputFolder = JoinPath(baseFolder, rootName & "_VISUAL_BOM_EXPORT")
    gImageFolder = JoinPath(gOutputFolder, "IMAGES")
    gMainImagePath = JoinPath(gOutputFolder, "MAIN_ASSEMBLY." & EffectiveImageFormat())
    gExcelPath = JoinPath(gOutputFolder, "VISUAL_BOM_EXPORT.xlsx")

    EnsureFolder gOutputFolder
    EnsureFolder gImageFolder
End Sub

Private Function EffectiveImageFormat() As String
    If FAST_SNIP_MODE Then
        EffectiveImageFormat = LCase$(FAST_IMAGE_FORMAT)
    Else
        EffectiveImageFormat = LCase$(IMAGE_FORMAT)
    End If
    If EffectiveImageFormat = "" Then EffectiveImageFormat = "jpg"
End Function

Private Function GetDocumentFolder(ByVal doc As Object) As String
    On Error Resume Next
    GetDocumentFolder = CStr(doc.Path)
    If Err.Number <> 0 Then
        Err.Clear
        GetDocumentFolder = ""
    End If
End Function

Private Sub BuildBomFromProductTree(ByVal rootProduct As Object)
    Dim selectedProducts As Collection
    Set selectedProducts = GetSelectedProducts()

    Dim rootPath As String
    rootPath = FirstNonEmpty(GetProductPartNumber(rootProduct), rootProduct.Name, "ROOT")

    Dim pathProducts As Collection
    Set pathProducts = New Collection
    pathProducts.Add rootProduct

    TraverseProductChildren rootProduct, "", rootPath, pathProducts, selectedProducts, False
End Sub

Private Sub TraverseProductChildren(ByVal parentProduct As Object, _
                                    ByVal parentAssemblyName As String, _
                                    ByVal parentTreePath As String, _
                                    ByVal parentPathProducts As Collection, _
                                    ByVal selectedProducts As Collection, _
                                    ByVal parentWasSelected As Boolean)
    On Error GoTo TraverseError

    Dim children As Object
    Set children = parentProduct.Products

    Dim i As Long
    For i = 1 To children.Count
        Dim child As Object
        Set child = children.Item(i)

        gAllProducts.Add child

        Dim childPartNumber As String
        Dim childLabel As String
        Dim childTreePath As String
        Dim childPathProducts As Collection
        Dim childSelected As Boolean

        childPartNumber = GetProductPartNumber(child)
        childLabel = FirstNonEmpty(childPartNumber, child.Name, "ITEM_" & CStr(gAllProducts.Count))
        childTreePath = parentTreePath & "\" & childLabel

        Set childPathProducts = CloneCollection(parentPathProducts)
        childPathProducts.Add child

        childSelected = parentWasSelected Or IsProductInSelection(child, selectedProducts)

        If ShouldExportProduct(child, childSelected) Then
            AddOrUpdateBomItem child, parentAssemblyName, childTreePath, childPathProducts
        End If

        If HasChildren(child) Then
            TraverseProductChildren child, childLabel, childTreePath, childPathProducts, selectedProducts, childSelected
        End If
    Next i
    Exit Sub

TraverseError:
    AddLog "", "WARNING", "Ne mogu potpuno da procitam decu sklopa '" & SafeText(parentProduct.Name) & "': " & Err.Description, ""
    Err.Clear
End Sub

Private Function GetSelectedProducts() As Collection
    Set GetSelectedProducts = New Collection
    If Not EXPORT_SELECTED_ONLY Then Exit Function

    On Error Resume Next
    Dim sel As Object
    Set sel = gActiveDoc.Selection
    If sel Is Nothing Then Exit Function

    Dim i As Long
    For i = 1 To sel.Count2
        Dim obj As Object
        Set obj = sel.Item2(i).Value
        If IsProductObject(obj) Then GetSelectedProducts.Add obj
    Next i
    Err.Clear
End Function

Private Function IsProductInSelection(ByVal prod As Object, ByVal selectedProducts As Collection) As Boolean
    If Not EXPORT_SELECTED_ONLY Then
        IsProductInSelection = True
        Exit Function
    End If

    Dim i As Long
    For i = 1 To selectedProducts.Count
        If selectedProducts.Item(i) Is prod Then
            IsProductInSelection = True
            Exit Function
        End If
    Next i
End Function

Private Function ShouldExportProduct(ByVal prod As Object, ByVal selectedOrChildOfSelected As Boolean) As Boolean
    If EXPORT_SELECTED_ONLY And Not selectedOrChildOfSelected Then Exit Function

    Dim t As String
    t = GetProductBomType(prod)

    If SKIP_ASSEMBLIES And t = "Assembly" Then Exit Function

    If t = "Assembly" And EXPORT_ASSEMBLIES Then
        ShouldExportProduct = True
    ElseIf t = "Part" And EXPORT_PARTS Then
        ShouldExportProduct = True
    End If
End Function

Private Sub AddOrUpdateBomItem(ByVal prod As Object, _
                               ByVal parentAssemblyName As String, _
                               ByVal treePath As String, _
                               ByVal pathProducts As Collection)
    On Error GoTo AddError

    gTotalInstances = gTotalInstances + 1

    Dim pn As String
    Dim key As String
    Dim rec As Object

    pn = GetProductPartNumber(prod)
    If pn <> "" Then
        key = "PN|" & UCase$(Trim$(pn))
    Else
        key = "INSTANCE|" & UCase$(Trim$(treePath))
    End If

    If Not gBomItems.Exists(key) Then
        If MAX_ITEMS_TO_EXPORT > 0 And gBomItems.Count >= MAX_ITEMS_TO_EXPORT Then Exit Sub
    End If

    If gBomItems.Exists(key) Then
        Set rec = gBomItems.Item(key)
        rec.Item("Quantity") = CLng(rec.Item("Quantity")) + 1

        If InStr(1, rec.Item("ParentAssembly"), parentAssemblyName, vbTextCompare) = 0 Then
            If rec.Item("ParentAssembly") <> "" And parentAssemblyName <> "" Then
                rec.Item("ParentAssembly") = rec.Item("ParentAssembly") & "; " & parentAssemblyName
            ElseIf parentAssemblyName <> "" Then
                rec.Item("ParentAssembly") = parentAssemblyName
            End If
        End If

        If InStr(1, rec.Item("TreePath"), treePath, vbTextCompare) = 0 Then
            rec.Item("TreePath") = rec.Item("TreePath") & vbLf & treePath
        End If

        If CStr(rec.Item("Note")) = "" Then
            rec.Item("Note") = "Grouped by Part Number; metadata and preview from first instance."
        End If
    Else
        Set rec = CreateObject("Scripting.Dictionary")
        rec.Add "No", CLng(gBomItems.Count + 1)
        rec.Add "Quantity", CLng(1)
        rec.Add "PartNumber", pn
        rec.Add "Revision", GetProductRevision(prod)
        rec.Add "Type", GetProductBomType(prod)
        rec.Add "Nomenclature", GetProductNomenclature(prod)
        rec.Add "Material", GetPropertyValue(prod, "Material", "Materijal")
        rec.Add "Dimension", GetPropertyValue(prod, "Dimension", "Dimenzija")
        rec.Add "Mass", GetProductMass(prod)
        rec.Add "Standard", GetPropertyValue(prod, "Standard")
        rec.Add "ParentAssembly", parentAssemblyName
        rec.Add "TreePath", treePath
        rec.Add "ImageFile", ""
        rec.Add "ImagePath", ""
        rec.Add "ExportStatus", "PENDING"
        rec.Add "Note", IIf(pn = "", "Part Number missing; exported as separate instance.", "")
        rec.Add "Key", key
        rec.Add "PathProducts", pathProducts
        rec.Add "ProductRef", prod
        gBomItems.Add key, rec
    End If
    Exit Sub

AddError:
    AddLog pn, "WARNING", "BOM stavka nije dodata: " & Err.Description, ""
    Err.Clear
End Sub

Private Sub ExportAllImages()
    On Error Resume Next
    If Not EXPORT_IMAGES Then
        AddLog GetProductPartNumber(gRootProduct), "WARNING", "EXPORT_IMAGES=False; image export skipped.", ""
        Exit Sub
    End If

    TrySetCatiaWindowSize IMAGE_WIDTH, IMAGE_HEIGHT
    SafeRestoreCatiaSession
    ApplyImageCaptureView

    Dim mainStart As Double
    mainStart = Timer
    If CaptureCurrentViewer(gMainImagePath, mainStart, ImageTimeoutSeconds()) Then
        If ENABLE_IMAGE_CROP And Not FAST_SNIP_MODE Then CropImageToContent gMainImagePath
        AddLog GetProductPartNumber(gRootProduct), "OK", "Main assembly image exported.", gMainImagePath
    Else
        If HasTimedOut(mainStart, ImageTimeoutSeconds()) Then
            AddLog GetProductPartNumber(gRootProduct), "TIMEOUT", "Main assembly image export timed out.", gMainImagePath
        Else
            AddLog GetProductPartNumber(gRootProduct), "ERROR", "Main assembly image export failed.", gMainImagePath
        End If
    End If

    Dim key As Variant
    Dim itemIndex As Long
    itemIndex = 0
    For Each key In gBomItems.Keys
        itemIndex = itemIndex + 1
        If ShouldProcessExportIndex(itemIndex) Then
        Dim rec As Object
        Set rec = gBomItems.Item(CStr(key))
        ExportImageForBomRecord rec
        If CStr(rec.Item("ExportStatus")) = "ERROR" Or CStr(rec.Item("ExportStatus")) = "NOT FOUND" Or CStr(rec.Item("ExportStatus")) = "TIMEOUT" Then SafeRestoreCatiaSession
        DoEvents
        End If
    Next key

    SafeRestoreCatiaSession
End Sub

Private Sub ExportImageForBomRecord(ByVal rec As Object)
    On Error GoTo ExportError

    Dim productRef As Object
    Dim pathProducts As Collection
    Dim imagePath As String
    Dim imageFile As String
    Dim itemStart As Double
    Dim itemTimeout As Double

    Set productRef = rec.Item("ProductRef")
    Set pathProducts = rec.Item("PathProducts")
    itemStart = Timer
    itemTimeout = ImageTimeoutSeconds()

    imageFile = BuildUniqueImageFileName(CStr(rec.Item("PartNumber")), CStr(rec.Item("Nomenclature")), CLng(rec.Item("No")))
    imagePath = JoinPath(gImageFolder, imageFile)

    If SKIP_EXISTING_IMAGES And gFSO.FileExists(imagePath) Then
        rec.Item("ImageFile") = gFSO.GetFileName(imagePath)
        rec.Item("ImagePath") = imagePath
        rec.Item("ExportStatus") = "OK"
        rec.Item("Note") = AppendNote(CStr(rec.Item("Note")), "Existing image reused.")
        AddLog CStr(rec.Item("PartNumber")), "OK", "Existing image reused.", imagePath
        Exit Sub
    End If

    HideAllComponents
    ShowProductPath pathProducts
    ShowProductSubtree productRef
    If HasTimedOut(itemStart, itemTimeout) Then
        rec.Item("ImageFile") = imageFile
        rec.Item("ImagePath") = imagePath
        rec.Item("ExportStatus") = "TIMEOUT"
        rec.Item("Note") = AppendNote(CStr(rec.Item("Note")), "Image export timeout during hide/show.")
        AddLog CStr(rec.Item("PartNumber")), "TIMEOUT", "Image export timeout during hide/show.", imagePath
        Exit Sub
    End If

    ApplyImageCaptureView

    If HasTimedOut(itemStart, itemTimeout) Then
        rec.Item("ImageFile") = imageFile
        rec.Item("ImagePath") = imagePath
        rec.Item("ExportStatus") = "TIMEOUT"
        rec.Item("Note") = AppendNote(CStr(rec.Item("Note")), "Image export timeout before capture.")
        AddLog CStr(rec.Item("PartNumber")), "TIMEOUT", "Image export timeout before capture.", imagePath
        Exit Sub
    End If

    If CaptureCurrentViewer(imagePath, itemStart, itemTimeout) Then
        If ENABLE_IMAGE_CROP And Not FAST_SNIP_MODE Then CropImageToContent imagePath
        imageFile = gFSO.GetFileName(imagePath)
        rec.Item("ImageFile") = imageFile
        rec.Item("ImagePath") = imagePath
        rec.Item("ExportStatus") = "OK"
        AddLog CStr(rec.Item("PartNumber")), "OK", "Image exported.", imagePath
    Else
        rec.Item("ImageFile") = imageFile
        rec.Item("ImagePath") = imagePath
        If HasTimedOut(itemStart, itemTimeout) Then
            rec.Item("ExportStatus") = "TIMEOUT"
            rec.Item("Note") = AppendNote(CStr(rec.Item("Note")), "Image export timeout.")
            AddLog CStr(rec.Item("PartNumber")), "TIMEOUT", "Image export timeout.", imagePath
        Else
            rec.Item("ExportStatus") = "ERROR"
            rec.Item("Note") = AppendNote(CStr(rec.Item("Note")), "Image export failed.")
            AddLog CStr(rec.Item("PartNumber")), "ERROR", "Image export failed.", imagePath
        End If
    End If

    Exit Sub

ExportError:
    rec.Item("ExportStatus") = "ERROR"
    rec.Item("Note") = AppendNote(CStr(rec.Item("Note")), "Image export error: " & Err.Description)
    AddLog CStr(rec.Item("PartNumber")), "ERROR", "Image export error: " & Err.Description, ""
    Err.Clear
End Sub

Private Function CaptureCurrentViewer(ByRef targetPath As String, Optional ByVal startTime As Double = 0, Optional ByVal timeoutSeconds As Double = 0) As Boolean
    On Error GoTo CaptureFailed
    If startTime <= 0 Then startTime = Timer
    If timeoutSeconds <= 0 Then timeoutSeconds = ImageTimeoutSeconds()

    If FAST_SNIP_MODE Then
        CaptureCurrentViewer = CaptureFastSnip(targetPath, startTime, timeoutSeconds)
        Exit Function
    End If

    Dim viewer As Object
    Set viewer = CATIA.ActiveWindow.ActiveViewer
    viewer.Activate
    viewer.Update
    WaitSeconds IMAGE_CAPTURE_DELAY_SECONDS
    If HasTimedOut(startTime, timeoutSeconds) Then Exit Function

    Dim ext As String
    ext = LCase$(gFSO.GetExtensionName(targetPath))

    If ext = "png" Then
        Dim tempBmp As String
        tempBmp = JoinPath(gOutputFolder, "~catia_capture_temp_" & Format(Now, "yyyymmdd_hhnnss") & "_" & CStr(Int(Rnd() * 100000)) & ".bmp")
        viewer.CaptureToFile CAT_CAPTURE_FORMAT_BMP, tempBmp
        WaitSeconds 0.1
        If HasTimedOut(startTime, timeoutSeconds) Then Exit Function

        If gFSO.FileExists(tempBmp) Then
            If ConvertImageWithWia(tempBmp, targetPath, WIA_FORMAT_PNG) Then
                On Error Resume Next
                gFSO.DeleteFile tempBmp, True
                On Error GoTo CaptureFailed
                CaptureCurrentViewer = gFSO.FileExists(targetPath)
                Exit Function
            Else
                Dim jpgFallback As String
                jpgFallback = Left$(targetPath, Len(targetPath) - Len(ext)) & "jpg"
                viewer.CaptureToFile CAT_CAPTURE_FORMAT_JPEG, jpgFallback
                If HasTimedOut(startTime, timeoutSeconds) Then Exit Function
                If gFSO.FileExists(jpgFallback) Then
                    AddLog "", "WARNING", "PNG conversion through WIA failed; JPEG fallback created.", jpgFallback
                    CaptureCurrentViewer = True
                    targetPath = jpgFallback
                    On Error Resume Next
                    gFSO.DeleteFile tempBmp, True
                    Exit Function
                End If
            End If
        End If
    ElseIf ext = "jpg" Or ext = "jpeg" Then
        viewer.CaptureToFile CAT_CAPTURE_FORMAT_JPEG, targetPath
    ElseIf ext = "tif" Or ext = "tiff" Then
        viewer.CaptureToFile CAT_CAPTURE_FORMAT_TIFF, targetPath
    Else
        viewer.CaptureToFile CAT_CAPTURE_FORMAT_BMP, targetPath
    End If

    If Not HasTimedOut(startTime, timeoutSeconds) Then CaptureCurrentViewer = gFSO.FileExists(targetPath)
    Exit Function

CaptureFailed:
    CaptureCurrentViewer = False
    Err.Clear
End Function

Private Function CaptureFastSnip(ByRef targetPath As String, ByVal startTime As Double, ByVal timeoutSeconds As Double) As Boolean
    On Error GoTo FastFailed
    If HasTimedOut(startTime, timeoutSeconds) Then Exit Function

    Dim viewer As Object
    Dim fastPath As String
    fastPath = ReplaceFileExtension(targetPath, EffectiveImageFormat())

    Set viewer = CATIA.ActiveWindow.ActiveViewer
    viewer.Activate
    viewer.Update
    WaitSeconds FAST_CAPTURE_DELAY_SECONDS
    If HasTimedOut(startTime, timeoutSeconds) Then Exit Function

    If gFSO.FileExists(fastPath) Then gFSO.DeleteFile fastPath, True
    viewer.CaptureToFile CAT_CAPTURE_FORMAT_JPEG, fastPath
    WaitSeconds FAST_CAPTURE_DELAY_SECONDS
    If Not gFSO.FileExists(fastPath) Then Exit Function

    If ENABLE_IMAGE_CROP And Not HasTimedOut(startTime, timeoutSeconds) Then
        If Not CenterCropImageFile(fastPath, FAST_CENTER_CROP_PERCENT) Then
            AddLog "", "WARNING", "Fast center crop failed; uncropped JPG kept.", fastPath
        End If
    End If

    If HasTimedOut(startTime, timeoutSeconds) Then Exit Function

    targetPath = fastPath
    CaptureFastSnip = gFSO.FileExists(fastPath)
    Exit Function

FastFailed:
    CaptureFastSnip = False
    Err.Clear
End Function

Private Function CenterCropImageFile(ByVal imagePath As String, ByVal centerPercent As Double) As Boolean
    On Error Resume Next
    CenterCropImageFile = False

    If centerPercent <= 0# Or centerPercent >= 1# Then
        CenterCropImageFile = gFSO.FileExists(imagePath)
        Exit Function
    End If

    Dim img As Object
    Dim width As Long
    Dim height As Long
    Dim cropW As Long
    Dim cropH As Long
    Dim minX As Long
    Dim minY As Long

    Set img = CreateObject("WIA.ImageFile")
    img.LoadFile imagePath
    width = CLng(img.Width)
    height = CLng(img.Height)
    If width < 20 Or height < 20 Then Exit Function

    cropW = CLng(width * centerPercent)
    cropH = CLng(height * centerPercent)
    If cropW < 20 Or cropH < 20 Then Exit Function

    minX = CLng((width - cropW) / 2)
    minY = CLng((height - cropH) / 2)

    CenterCropImageFile = ApplyWiaCrop(imagePath, minX, minY, minX + cropW - 1, minY + cropH - 1)
    Err.Clear
End Function

Private Function ConvertImageWithWia(ByVal sourcePath As String, ByVal targetPath As String, ByVal formatId As String) As Boolean
    On Error GoTo WiaFailed

    If gFSO.FileExists(targetPath) Then gFSO.DeleteFile targetPath, True

    Dim img As Object
    Dim proc As Object
    Dim converted As Object

    Set img = CreateObject("WIA.ImageFile")
    img.LoadFile sourcePath

    Set proc = CreateObject("WIA.ImageProcess")
    proc.Filters.Add proc.FilterInfos("Convert").FilterID
    proc.Filters(1).Properties("FormatID").Value = formatId

    Set converted = proc.Apply(img)
    converted.SaveFile targetPath

    ConvertImageWithWia = gFSO.FileExists(targetPath)
    Exit Function

WiaFailed:
    ConvertImageWithWia = False
    Err.Clear
End Function

Private Function CropImageToContent(ByVal imagePath As String) As Boolean
    On Error Resume Next
    CropImageToContent = False
    If Not ENABLE_IMAGE_CROP Then
        CropImageToContent = True
        Exit Function
    End If
    If Not gFSO.FileExists(imagePath) Then Exit Function
    If FAST_SNIP_MODE Then
        CropImageToContent = CenterCropImageFile(imagePath, FAST_CENTER_CROP_PERCENT)
        Exit Function
    End If

    If AUTO_CROP_WHITE_BACKGROUND Then
        If AutoCropWhiteBackground(imagePath) Then
            CropImageToContent = True
            Exit Function
        End If
    End If

    If FixedCropImageFile(imagePath, FALLBACK_FIXED_CROP_PERCENT) Then
        CropImageToContent = True
    Else
        AddLog "", "WARNING", "Image crop failed; original image kept.", imagePath
    End If
    Err.Clear
End Function

Private Function CropImageFile(ByVal imagePath As String) As Boolean
    CropImageFile = CropImageToContent(imagePath)
End Function

Private Function AutoCropWhiteBackground(ByVal imagePath As String) As Boolean
    On Error Resume Next
    AutoCropWhiteBackground = False

    Dim img As Object
    Dim pixels As Object
    Dim width As Long
    Dim height As Long
    Dim scanStep As Long
    Dim baseIndex As Long
    Dim x As Long
    Dim y As Long
    Dim idx As Long
    Dim pixel As Variant
    Dim minX As Long
    Dim minY As Long
    Dim maxX As Long
    Dim maxY As Long
    Dim padX As Long
    Dim padY As Long
    Dim foundCount As Long

    Set img = CreateObject("WIA.ImageFile")
    img.LoadFile imagePath
    width = CLng(img.Width)
    height = CLng(img.Height)
    If width < 20 Or height < 20 Then Exit Function

    Set pixels = img.ARGBData
    Err.Clear
    pixel = pixels.Item(0)
    If Err.Number <> 0 Then
        Err.Clear
        baseIndex = 1
    Else
        baseIndex = 0
    End If

    scanStep = 1

    minX = width
    minY = height
    maxX = -1
    maxY = -1

    For y = 0 To height - 1 Step scanStep
        DoEvents
        For x = 0 To width - 1 Step scanStep
            idx = baseIndex + (y * width) + x
            pixel = pixels.Item(idx)
            If Err.Number = 0 Then
                If PixelLooksLikeForeground(pixel) Then
                    foundCount = foundCount + 1
                    If x < minX Then minX = x
                    If y < minY Then minY = y
                    If x > maxX Then maxX = x
                    If y > maxY Then maxY = y
                End If
            End If
            Err.Clear
        Next x
    Next y

    If foundCount < 20 Then Exit Function
    If maxX <= minX Or maxY <= minY Then Exit Function
    If (maxX - minX) < width * 0.05 Or (maxY - minY) < height * 0.05 Then Exit Function

    padX = CLng((maxX - minX + 1) * CROP_PADDING_PERCENT)
    padY = CLng((maxY - minY + 1) * CROP_PADDING_PERCENT)
    If padX < 8 Then padX = 8
    If padY < 8 Then padY = 8

    minX = minX - padX
    minY = minY - padY
    maxX = maxX + padX
    maxY = maxY + padY
    If minX < 0 Then minX = 0
    If minY < 0 Then minY = 0
    If maxX > width - 1 Then maxX = width - 1
    If maxY > height - 1 Then maxY = height - 1

    AutoCropWhiteBackground = ApplyWiaCrop(imagePath, minX, minY, maxX, maxY)
    Err.Clear
End Function

Private Function PixelLooksLikeForeground(ByVal pixelValue As Variant) As Boolean
    On Error Resume Next
    Dim p As Double
    Dim r As Long
    Dim g As Long
    Dim b As Long
    Dim t As Double

    p = CDbl(pixelValue)
    If p < 0 Then p = p + 4294967296#
    b = CLng(p - (256 * Int(p / 256)))
    t = Int(p / 256)
    g = CLng(t - (256 * Int(t / 256)))
    t = Int(p / 65536)
    r = CLng(t - (256 * Int(t / 256)))

    PixelLooksLikeForeground = (r < WHITE_THRESHOLD Or g < WHITE_THRESHOLD Or b < WHITE_THRESHOLD)
    Err.Clear
End Function

Private Function FixedCropImageFile(ByVal imagePath As String, ByVal marginPercent As Double) As Boolean
    On Error Resume Next
    FixedCropImageFile = False

    Dim img As Object
    Dim width As Long
    Dim height As Long
    Dim dx As Long
    Dim dy As Long
    Set img = CreateObject("WIA.ImageFile")
    img.LoadFile imagePath
    width = CLng(img.Width)
    height = CLng(img.Height)
    If width < 20 Or height < 20 Then Exit Function
    dx = CLng(width * marginPercent)
    dy = CLng(height * marginPercent)
    FixedCropImageFile = ApplyWiaCrop(imagePath, dx, dy, width - dx - 1, height - dy - 1)
    Err.Clear
End Function

Private Function ApplyWiaCrop(ByVal imagePath As String, ByVal minX As Long, ByVal minY As Long, ByVal maxX As Long, ByVal maxY As Long) As Boolean
    On Error Resume Next
    ApplyWiaCrop = False

    Dim img As Object
    Dim proc As Object
    Dim cropped As Object
    Dim tmpPath As String
    Dim width As Long
    Dim height As Long

    Set img = CreateObject("WIA.ImageFile")
    img.LoadFile imagePath
    width = CLng(img.Width)
    height = CLng(img.Height)

    If minX < 0 Then minX = 0
    If minY < 0 Then minY = 0
    If maxX > width - 1 Then maxX = width - 1
    If maxY > height - 1 Then maxY = height - 1
    If maxX <= minX Or maxY <= minY Then Exit Function

    Set proc = CreateObject("WIA.ImageProcess")
    proc.Filters.Add proc.FilterInfos("Crop").FilterID
    proc.Filters(1).Properties("Left").Value = CLng(minX)
    proc.Filters(1).Properties("Top").Value = CLng(minY)
    proc.Filters(1).Properties("Right").Value = CLng(width - maxX - 1)
    proc.Filters(1).Properties("Bottom").Value = CLng(height - maxY - 1)

    Set cropped = proc.Apply(img)
    tmpPath = JoinPath(gOutputFolder, "~crop_" & Format(Now, "yyyymmdd_hhnnss") & "_" & CStr(Int(Rnd() * 100000)) & "." & gFSO.GetExtensionName(imagePath))
    If gFSO.FileExists(tmpPath) Then gFSO.DeleteFile tmpPath, True
    cropped.SaveFile tmpPath

    If Err.Number = 0 And gFSO.FileExists(tmpPath) Then
        gFSO.CopyFile tmpPath, imagePath, True
        gFSO.DeleteFile tmpPath, True
        ApplyWiaCrop = gFSO.FileExists(imagePath)
    End If
    Err.Clear
End Function

Private Sub HideAllComponents()
    SetVisibilityForCollection gAllProducts, False
End Sub

Private Sub ShowProductPath(ByVal pathProducts As Collection)
    SetVisibilityForCollection pathProducts, True
End Sub

Private Sub ShowProductSubtree(ByVal productRoot As Object)
    On Error Resume Next

    Dim subtree As Collection
    Set subtree = New Collection
    CollectSubtreeProducts productRoot, subtree
    SetVisibilityForCollection subtree, True
    Err.Clear
End Sub

Private Sub CollectSubtreeProducts(ByVal productRoot As Object, ByVal result As Collection)
    On Error Resume Next

    result.Add productRoot

    Dim children As Object
    Set children = productRoot.Products
    If Err.Number <> 0 Or children Is Nothing Then
        Err.Clear
        Exit Sub
    End If

    Dim i As Long
    For i = 1 To children.Count
        CollectSubtreeProducts children.Item(i), result
    Next i
    Err.Clear
End Sub

Private Sub RestoreWholeAssemblyView()
    On Error Resume Next
    SetVisibilityForCollection gAllProducts, True
    ApplyIsoViewAndFit
    gActiveDoc.Selection.Clear
    Err.Clear
End Sub

Private Sub SafeRestoreCatiaSession()
    On Error Resume Next
    CATIA.RefreshDisplay = True
    If Not gActiveDoc Is Nothing Then gActiveDoc.Selection.Clear
    If Not gAllProducts Is Nothing Then SetVisibilityForCollection gAllProducts, True
    If Not gRootProduct Is Nothing Then
        gActiveDoc.Selection.Clear
        gActiveDoc.Selection.Add gRootProduct
        gActiveDoc.Selection.VisProperties.SetShow CAT_VIS_PROPERTY_SHOW
        gActiveDoc.Selection.Clear
    End If
    CATIA.RefreshDisplay = True
    ApplyIsoViewAndFit
    If Not gActiveDoc Is Nothing Then gActiveDoc.Selection.Clear
    CATIA.StatusBar = ""
    Err.Clear
End Sub

Private Sub SetVisibilityForCollection(ByVal products As Collection, ByVal showIt As Boolean)
    On Error Resume Next

    Dim sel As Object
    Set sel = gActiveDoc.Selection
    sel.Clear

    Dim i As Long
    For i = 1 To products.Count
        sel.Add products.Item(i)
        If (i Mod 200) = 0 Then
            If showIt Then
                sel.VisProperties.SetShow CAT_VIS_PROPERTY_SHOW
            Else
                sel.VisProperties.SetShow CAT_VIS_PROPERTY_NO_SHOW
            End If
            sel.Clear
        End If
    Next i

    If sel.Count2 > 0 Then
        If showIt Then
            sel.VisProperties.SetShow CAT_VIS_PROPERTY_SHOW
        Else
            sel.VisProperties.SetShow CAT_VIS_PROPERTY_NO_SHOW
        End If
    End If

    sel.Clear
    CATIA.RefreshDisplay = True
    WaitSeconds 0.1
    Err.Clear
End Sub

Private Sub ApplyImageCaptureView()
    If FAST_SNIP_MODE Then
        ApplyFastSnipView
    Else
        ApplyIsoViewAndFit
    End If
End Sub

Private Sub ApplyFastSnipView()
    On Error Resume Next

    Dim viewer As Object
    Set viewer = CATIA.ActiveWindow.ActiveViewer
    viewer.Activate

    If USE_NICE_IMAGE_VIEW Then
        If USE_SHADED_WITH_EDGES Then
            Err.Clear
            viewer.RenderingMode = CAT_RENDER_SHADING_WITH_EDGES
            If Err.Number <> 0 Then
                Err.Clear
                viewer.RenderingMode = CAT_RENDER_SHADING
            End If
        Else
            Err.Clear
            viewer.RenderingMode = CAT_RENDER_SHADING
        End If

        If USE_WHITE_BACKGROUND Then
            Err.Clear
            Dim bg(2) As Double
            bg(0) = 1#
            bg(1) = 1#
            bg(2) = 1#
            viewer.PutBackgroundColor bg
            Err.Clear
        End If
    End If

    Dim vp As Object
    Set vp = viewer.Viewpoint3D

    Dim sight(2) As Double
    Dim up(2) As Double
    sight(0) = 1#
    sight(1) = -1#
    sight(2) = 1#
    up(0) = -0.4082482905
    up(1) = 0.4082482905
    up(2) = 0.8164965809

    vp.PutSightDirection sight
    vp.PutUpDirection up
    If USE_PARALLEL_PROJECTION Then
        Err.Clear
        vp.ProjectionMode = CAT_PROJECTION_CYLINDRIC
        Err.Clear
    End If

    viewer.Update
    viewer.Reframe
    viewer.Update
    DoEvents

    If FAST_ZOOM_IN_STEPS > 0 Then
        Dim i As Long
        For i = 1 To FAST_ZOOM_IN_STEPS
            viewer.ZoomIn
            viewer.Update
            DoEvents
        Next i
    End If

    viewer.Update
    WaitSeconds FAST_CAPTURE_DELAY_SECONDS
    Err.Clear
End Sub

Private Sub ApplyIsoViewAndFit()
    On Error Resume Next

    Dim viewer As Object
    Set viewer = CATIA.ActiveWindow.ActiveViewer
    viewer.Activate

    If USE_NICE_IMAGE_VIEW Then
        If USE_SHADED_WITH_EDGES Then
            Err.Clear
            viewer.RenderingMode = CAT_RENDER_SHADING_WITH_EDGES
            If Err.Number <> 0 Then
                Err.Clear
                viewer.RenderingMode = CAT_RENDER_SHADING
            End If
        Else
            Err.Clear
            viewer.RenderingMode = CAT_RENDER_SHADING
        End If

        If USE_WHITE_BACKGROUND Then
            Err.Clear
            Dim bg(2) As Double
            bg(0) = 1#
            bg(1) = 1#
            bg(2) = 1#
            viewer.PutBackgroundColor bg
            Err.Clear
        End If
    End If

    Dim vp As Object
    Set vp = viewer.Viewpoint3D

    Dim sight(2) As Double
    Dim up(2) As Double
    sight(0) = 1#
    sight(1) = -1#
    sight(2) = 1#
    up(0) = -0.4082482905
    up(1) = 0.4082482905
    up(2) = 0.8164965809

    vp.PutSightDirection sight
    vp.PutUpDirection up
    If USE_PARALLEL_PROJECTION Then
        Err.Clear
        vp.ProjectionMode = CAT_PROJECTION_CYLINDRIC
        Err.Clear
    End If

    Dim i As Long
    For i = 1 To IMAGE_FIT_REPEAT_COUNT
        viewer.Update
        viewer.Reframe
        viewer.Update
        DoEvents
    Next i

    viewer.ZoomOut

    Dim zoomSteps As Long
    zoomSteps = IMAGE_EXTRA_ZOOM_OUT_STEPS
    If zoomSteps < 0 Then zoomSteps = 0
    For i = 1 To zoomSteps
        viewer.ZoomOut
        viewer.Update
        DoEvents
    Next i

    viewer.Update
    WaitSeconds IMAGE_CAPTURE_DELAY_SECONDS
    Err.Clear
End Sub

Private Sub TrySetCatiaWindowSize(ByVal widthPx As Long, ByVal heightPx As Long)
    On Error Resume Next
    CATIA.ActiveWindow.Width = widthPx
    CATIA.ActiveWindow.Height = heightPx
    CATIA.ActiveWindow.ActiveViewer.Update
    Err.Clear
End Sub

Private Sub InitializeBomHeaders()
    On Error Resume Next
    Set gBomHeaders = New Collection
    gCatiaBomColumnsSource = "fallback"

    ' Primary path: CATIA Product.ExtractBOM uses the current Analyze > Bill of Material format.
    ' Some V5 releases expose only the generated file, not the checked format list directly.
    If USE_CATIA_DEFINED_BOM_COLUMNS Then
        If TryLoadCatiaNativeBomHeaders() Then gCatiaBomColumnsSource = "CATIA ExtractBOM"
    End If

    If gBomHeaders.Count = 0 Then LoadFallbackBomHeaders
    EnsureBomUtilityColumns
    Err.Clear
End Sub

Private Function TryLoadCatiaNativeBomHeaders() As Boolean
    On Error Resume Next
    Dim fileTypes As Variant
    Dim fileExts As Variant
    Dim i As Long
    Dim bomPath As String

    fileTypes = Array(CAT_FILE_TYPE_TXT, 1, CAT_FILE_TYPE_HTML)
    fileExts = Array("txt", "txt", "html")

    For i = LBound(fileTypes) To UBound(fileTypes)
        bomPath = JoinPath(gOutputFolder, "~CATIA_NATIVE_BOM_HEADERS." & CStr(fileExts(i)))
        If gFSO.FileExists(bomPath) Then gFSO.DeleteFile bomPath, True
        Err.Clear
        gRootProduct.ExtractBOM CLng(fileTypes(i)), bomPath
        If Err.Number = 0 And gFSO.FileExists(bomPath) Then
            If LoadBomHeadersFromFile(bomPath) Then
                TryLoadCatiaNativeBomHeaders = True
                Exit Function
            End If
        End If
        Err.Clear
    Next i
End Function

Private Function LoadBomHeadersFromFile(ByVal filePath As String) As Boolean
    On Error Resume Next
    Dim ts As Object
    Dim txt As String
    Set ts = gFSO.OpenTextFile(filePath, 1, False)
    If Err.Number <> 0 Then
        Err.Clear
        Exit Function
    End If
    txt = ts.ReadAll
    ts.Close

    If InStr(1, LCase$(filePath), ".htm", vbTextCompare) > 0 Then
        LoadBomHeadersFromFile = LoadHeadersFromHtmlText(txt)
    Else
        LoadBomHeadersFromFile = LoadHeadersFromDelimitedText(txt)
    End If
    Err.Clear
End Function

Private Function LoadHeadersFromDelimitedText(ByVal txt As String) As Boolean
    On Error Resume Next
    Dim lines As Variant
    Dim i As Long
    Dim line As String
    Dim delimiter As String
    Dim cells As Variant

    lines = Split(Replace(txt, vbCr, vbLf), vbLf)
    For i = LBound(lines) To UBound(lines)
        line = Trim$(CStr(lines(i)))
        If line <> "" Then
            delimiter = DetectBomDelimiter(line)
            If delimiter <> "" Then
                cells = Split(line, delimiter)
                If CountUsefulCells(cells) >= 2 And LooksLikeBomHeaderLine(line) Then
                    AddHeaderArray cells
                    LoadHeadersFromDelimitedText = (gBomHeaders.Count > 0)
                    Exit Function
                End If
            End If
        End If
    Next i

    For i = LBound(lines) To UBound(lines)
        line = Trim$(CStr(lines(i)))
        delimiter = DetectBomDelimiter(line)
        If delimiter <> "" Then
            cells = Split(line, delimiter)
            If CountUsefulCells(cells) >= 3 Then
                AddHeaderArray cells
                LoadHeadersFromDelimitedText = (gBomHeaders.Count > 0)
                Exit Function
            End If
        End If
    Next i
End Function

Private Function LoadHeadersFromHtmlText(ByVal txt As String) As Boolean
    On Error Resume Next
    Dim reTr As Object
    Dim reCell As Object
    Dim rows As Object
    Dim row As Object
    Dim cells As Object
    Dim cell As Object
    Dim tmp As Collection

    Set reTr = CreateObject("VBScript.RegExp")
    reTr.Global = True
    reTr.IgnoreCase = True
    reTr.Pattern = "<tr[^>]*>([\s\S]*?)</tr>"
    Set reCell = CreateObject("VBScript.RegExp")
    reCell.Global = True
    reCell.IgnoreCase = True
    reCell.Pattern = "<t[hd][^>]*>([\s\S]*?)</t[hd]>"

    Set rows = reTr.Execute(txt)
    For Each row In rows
        Set cells = reCell.Execute(row.SubMatches(0))
        If cells.Count >= 2 Then
            Set tmp = New Collection
            For Each cell In cells
                tmp.Add CleanHtmlText(cell.SubMatches(0))
            Next cell
            If LooksLikeHeaderCollection(tmp) Then
                CopyHeaderCollection tmp
                LoadHeadersFromHtmlText = (gBomHeaders.Count > 0)
                Exit Function
            End If
        End If
    Next row
End Function

Private Function DetectBomDelimiter(ByVal line As String) As String
    If InStr(line, vbTab) > 0 Then
        DetectBomDelimiter = vbTab
    ElseIf InStr(line, "|") > 0 Then
        DetectBomDelimiter = "|"
    ElseIf InStr(line, ";") > 0 Then
        DetectBomDelimiter = ";"
    ElseIf InStr(line, ",") > 0 Then
        DetectBomDelimiter = ","
    End If
End Function

Private Function CountUsefulCells(ByVal cells As Variant) As Long
    Dim i As Long
    For i = LBound(cells) To UBound(cells)
        If Trim$(CStr(cells(i))) <> "" Then CountUsefulCells = CountUsefulCells + 1
    Next i
End Function

Private Function LooksLikeBomHeaderLine(ByVal line As String) As Boolean
    Dim l As String
    l = LCase$(line)
    LooksLikeBomHeaderLine = (InStr(l, "part") > 0 Or InStr(l, "qty") > 0 Or InStr(l, "quantity") > 0 Or _
                              InStr(l, "nomen") > 0 Or InStr(l, "material") > 0 Or InStr(l, "mass") > 0 Or _
                              InStr(l, "item") > 0 Or InStr(l, "dimenz") > 0)
End Function

Private Function LooksLikeHeaderCollection(ByVal headers As Collection) As Boolean
    Dim i As Long
    Dim joined As String
    For i = 1 To headers.Count
        joined = joined & " " & LCase$(CStr(headers.Item(i)))
    Next i
    LooksLikeHeaderCollection = LooksLikeBomHeaderLine(joined)
End Function

Private Sub AddHeaderArray(ByVal cells As Variant)
    Dim i As Long
    Dim h As String
    Set gBomHeaders = New Collection
    For i = LBound(cells) To UBound(cells)
        h = CleanHeaderText(CStr(cells(i)))
        If h <> "" Then AddUniqueHeader h
    Next i
End Sub

Private Sub CopyHeaderCollection(ByVal sourceHeaders As Collection)
    Dim i As Long
    Dim h As String
    Set gBomHeaders = New Collection
    For i = 1 To sourceHeaders.Count
        h = CleanHeaderText(CStr(sourceHeaders.Item(i)))
        If h <> "" Then AddUniqueHeader h
    Next i
End Sub

Private Sub LoadFallbackBomHeaders()
    AddHeaderArray Split(BOM_COLUMNS, "|")
End Sub

Private Sub AddUniqueHeader(ByVal headerText As String)
    If FindHeaderIndex(headerText) = 0 Then gBomHeaders.Add headerText
End Sub

Private Function FindHeaderIndex(ByVal headerText As String) As Long
    Dim i As Long
    Dim target As String
    target = NormalizeHeaderName(headerText)
    For i = 1 To gBomHeaders.Count
        If NormalizeHeaderName(CStr(gBomHeaders.Item(i))) = target Then
            FindHeaderIndex = i
            Exit Function
        End If
    Next i
End Function

Private Sub EnsureBomUtilityColumns()
    Dim insertAfter As Long
    insertAfter = FindHeaderIndex("Part Number")
    If insertAfter = 0 Then insertAfter = FindHeaderIndex("Item")
    If insertAfter = 0 Then insertAfter = 1

    gThumbnailColumnIndex = FindHeaderIndex("Thumbnail")
    If gThumbnailColumnIndex = 0 Then
        InsertHeaderAt insertAfter + 1, "Thumbnail"
        gThumbnailColumnIndex = FindHeaderIndex("Thumbnail")
    End If

    If FindHeaderIndex("Image Path") = 0 Then AddUniqueHeader "Image Path"
    If FindHeaderIndex("Export Status") = 0 Then AddUniqueHeader "Export Status"
    gImagePathColumnIndex = FindHeaderIndex("Image Path")
    gExportStatusColumnIndex = FindHeaderIndex("Export Status")
End Sub

Private Sub InsertHeaderAt(ByVal position As Long, ByVal headerText As String)
    Dim newHeaders As Collection
    Dim i As Long
    Set newHeaders = New Collection
    If position < 1 Then position = 1
    If position > gBomHeaders.Count + 1 Then position = gBomHeaders.Count + 1
    For i = 1 To gBomHeaders.Count + 1
        If i = position Then newHeaders.Add headerText
        If i <= gBomHeaders.Count Then newHeaders.Add CStr(gBomHeaders.Item(i))
    Next i
    Set gBomHeaders = newHeaders
End Sub

Private Function CleanHeaderText(ByVal valueText As String) As String
    CleanHeaderText = Trim$(Replace(Replace(CleanHtmlText(valueText), vbCr, " "), vbLf, " "))
End Function

Private Function CleanHtmlText(ByVal valueText As String) As String
    On Error Resume Next
    Dim re As Object
    Dim s As String
    s = CStr(valueText)
    Set re = CreateObject("VBScript.RegExp")
    re.Global = True
    re.IgnoreCase = True
    re.Pattern = "<[^>]+>"
    s = re.Replace(s, "")
    s = Replace(s, "&nbsp;", " ")
    s = Replace(s, "&amp;", "&")
    s = Replace(s, "&lt;", "<")
    s = Replace(s, "&gt;", ">")
    s = Replace(s, Chr$(160), " ")
    CleanHtmlText = Trim$(s)
    Err.Clear
End Function

Private Function NormalizeHeaderName(ByVal valueText As String) As String
    Dim s As String
    s = LCase$(Trim$(CStr(valueText)))
    s = Replace(s, ".", "")
    s = Replace(s, "_", "")
    s = Replace(s, "-", "")
    s = Replace(s, " ", "")
    NormalizeHeaderName = s
End Function

Private Function GetBomCellValue(ByVal rec As Object, ByVal headerText As String) As String
    On Error Resume Next
    Select Case NormalizeHeaderName(headerText)
        Case "item", "no", "number", "rbr"
            GetBomCellValue = CStr(rec.Item("No"))
        Case "quantity", "qty", "qta", "qte"
            GetBomCellValue = CStr(rec.Item("Quantity"))
        Case "partnumber", "partno", "pn"
            GetBomCellValue = CStr(rec.Item("PartNumber"))
        Case "revision", "rev", "revizija"
            GetBomCellValue = CStr(rec.Item("Revision"))
        Case "type", "componenttype"
            GetBomCellValue = CStr(rec.Item("Type"))
        Case "nomenclature", "nomenklatura", "description", "opis"
            GetBomCellValue = CStr(rec.Item("Nomenclature"))
        Case "material", "materijal"
            GetBomCellValue = CStr(rec.Item("Material"))
        Case "dimension", "dimenzija", "dimmm", "dimensions"
            GetBomCellValue = CStr(rec.Item("Dimension"))
        Case "mass", "masa"
            GetBomCellValue = CStr(rec.Item("Mass"))
        Case "standard"
            GetBomCellValue = CStr(rec.Item("Standard"))
        Case "parentassembly"
            GetBomCellValue = CStr(rec.Item("ParentAssembly"))
        Case "treepath", "fulltreepath"
            GetBomCellValue = CStr(rec.Item("TreePath"))
        Case "imagefile"
            GetBomCellValue = CStr(rec.Item("ImageFile"))
        Case "imagepath"
            GetBomCellValue = CStr(rec.Item("ImagePath"))
        Case "exportstatus"
            GetBomCellValue = CStr(rec.Item("ExportStatus"))
        Case "note", "comments", "comment"
            GetBomCellValue = CStr(rec.Item("Note"))
        Case "thumbnail"
            GetBomCellValue = ""
        Case Else
            GetBomCellValue = GetPropertyValue(rec.Item("ProductRef"), headerText)
    End Select
    Err.Clear
End Function

Private Function ShouldProcessExportIndex(ByVal itemIndex As Long) As Boolean
    ShouldProcessExportIndex = True
    If START_INDEX > 1 And itemIndex < START_INDEX Then ShouldProcessExportIndex = False
    If END_INDEX > 0 And itemIndex > END_INDEX Then ShouldProcessExportIndex = False
End Function

Private Sub CreateExcelReport()
    On Error GoTo ExcelFatal

    Dim xl As Object
    Dim wb As Object
    Dim wsSummary As Object
    Dim wsBom As Object
    Dim wsLog As Object

    Set xl = CreateObject("Excel.Application")
    If xl Is Nothing Then
        MsgBox "Microsoft Excel nije dostupan preko COM automation.", vbCritical, "CATIA_VISUAL_BOM_EXPORTER"
        Exit Sub
    End If

    xl.Visible = False
    xl.DisplayAlerts = False

    Set wb = xl.Workbooks.Add
    Do While wb.Worksheets.Count < 3
        wb.Worksheets.Add After:=wb.Worksheets(wb.Worksheets.Count)
    Loop

    Set wsSummary = wb.Worksheets(1)
    Set wsBom = wb.Worksheets(2)
    Set wsLog = wb.Worksheets(3)

    wsSummary.Name = "SUMMARY"
    wsBom.Name = "BOM"
    wsLog.Name = "EXPORT_LOG"

    FillSummarySheet wsSummary
    FillBomSheet wsBom
    FillLogSheet wsLog

    xl.DisplayAlerts = False
    If gFSO.FileExists(gExcelPath) Then gFSO.DeleteFile gExcelPath, True
    wb.SaveAs gExcelPath, XL_OPENXML_WORKBOOK
    xl.Visible = True
    xl.DisplayAlerts = True
    Exit Sub

ExcelFatal:
    On Error Resume Next
    If Not xl Is Nothing Then
        xl.DisplayAlerts = True
        xl.Visible = True
    End If
    MsgBox "Excel izvestaj nije napravljen:" & vbCrLf & _
           Err.Number & " - " & Err.Description, vbCritical, "CATIA_VISUAL_BOM_EXPORTER"
End Sub

Private Sub FillSummarySheet(ByVal ws As Object)
    On Error Resume Next

    ws.Cells.Clear
    ws.Range("A1").Value = "CATIA VISUAL BOM EXPORTER"
    ws.Range("A3").Value = "Main Assembly Part Number"
    ws.Range("B3").Value = GetProductPartNumber(gRootProduct)
    ws.Range("A4").Value = "Main Assembly Nomenclature"
    ws.Range("B4").Value = GetProductNomenclature(gRootProduct)
    ws.Range("A5").Value = "Export Date/Time"
    ws.Range("B5").Value = Now
    ws.Range("A6").Value = "Distinct BOM Items"
    ws.Range("B6").Value = gBomItems.Count
    ws.Range("A7").Value = "Total Instances"
    ws.Range("B7").Value = gTotalInstances
    ws.Range("A8").Value = "Output Folder"
    ws.Range("B8").Value = gOutputFolder
    ws.Range("A10").Value = "Main Assembly Preview"

    ws.Range("A1:B1").Merge
    ws.Range("A1").Font.Bold = True
    ws.Range("A1").Font.Size = 16
    ws.Range("A3:A10").Font.Bold = True
    ws.Columns("A").ColumnWidth = 28
    ws.Columns("B").ColumnWidth = 90
    ws.Rows("11:28").RowHeight = 22

    If INSERT_IMAGES_IN_EXCEL And gFSO.FileExists(gMainImagePath) Then
        InsertPictureIntoRange ws, gMainImagePath, "A11:D28"
    End If

    ApplyUsedRangeBorders ws
End Sub

Private Sub FillBomSheet(ByVal ws As Object)
    On Error Resume Next

    ws.Cells.Clear

    Dim c As Long
    For c = 1 To gBomHeaders.Count
        ws.Cells(1, c).Value = gBomHeaders.Item(c)
    Next c

    Dim rowIndex As Long
    rowIndex = 2

    Dim key As Variant
    For Each key In gBomItems.Keys
        Dim rec As Object
        Set rec = gBomItems.Item(CStr(key))

        For c = 1 To gBomHeaders.Count
            If c <> gThumbnailColumnIndex Then ws.Cells(rowIndex, c).Value = GetBomCellValue(rec, CStr(gBomHeaders.Item(c)))
        Next c

        ws.Rows(rowIndex).RowHeight = IIf(INSERT_IMAGES_IN_EXCEL, CLng(THUMBNAIL_HEIGHT * 0.75) + 12, 28)

        If INSERT_IMAGES_IN_EXCEL And CStr(rec.Item("ImagePath")) <> "" And gFSO.FileExists(CStr(rec.Item("ImagePath"))) Then
            InsertPictureIntoCell ws, CStr(rec.Item("ImagePath")), ws.Cells(rowIndex, gThumbnailColumnIndex)
        End If

        rowIndex = rowIndex + 1
    Next key

    FormatBomSheet ws, rowIndex - 1
End Sub

Private Sub FillLogSheet(ByVal ws As Object)
    On Error Resume Next

    ws.Cells.Clear
    ws.Cells(1, 1).Value = "No."
    ws.Cells(1, 2).Value = "Date/Time"
    ws.Cells(1, 3).Value = "Part Number"
    ws.Cells(1, 4).Value = "Status"
    ws.Cells(1, 5).Value = "Message"
    ws.Cells(1, 6).Value = "Image Path"

    Dim i As Long
    For i = 1 To gExportLog.Count
        Dim rec As Object
        Set rec = gExportLog.Item(i)
        ws.Cells(i + 1, 1).Value = i
        ws.Cells(i + 1, 2).Value = rec.Item("DateTime")
        ws.Cells(i + 1, 3).Value = rec.Item("PartNumber")
        ws.Cells(i + 1, 4).Value = rec.Item("Status")
        ws.Cells(i + 1, 5).Value = rec.Item("Message")
        ws.Cells(i + 1, 6).Value = rec.Item("ImagePath")
    Next i

    ws.Rows(1).Font.Bold = True
    ws.Rows(1).Interior.Color = RGB(220, 230, 241)
    ws.Columns("A").ColumnWidth = 8
    ws.Columns("B").ColumnWidth = 22
    ws.Columns("C").ColumnWidth = 28
    ws.Columns("D").ColumnWidth = 14
    ws.Columns("E").ColumnWidth = 70
    ws.Columns("F").ColumnWidth = 90
    ws.Range("A1:F1").AutoFilter
    ws.Columns("A:F").VerticalAlignment = XL_TOP
    ApplyUsedRangeBorders ws
End Sub

Private Sub FormatBomSheet(ByVal ws As Object, ByVal lastRow As Long)
    On Error Resume Next

    ws.Rows(1).Font.Bold = True
    ws.Rows(1).Interior.Color = RGB(220, 230, 241)
    ws.Rows(1).HorizontalAlignment = XL_CENTER

    Dim c As Long
    For c = 1 To gBomHeaders.Count
        If c = gThumbnailColumnIndex Then
            ws.Columns(c).ColumnWidth = 24
        ElseIf c = gImagePathColumnIndex Then
            ws.Columns(c).ColumnWidth = 55
        ElseIf c = gExportStatusColumnIndex Then
            ws.Columns(c).ColumnWidth = 18
        Else
            ws.Columns(c).ColumnWidth = 22
        End If
    Next c

    If lastRow >= 2 Then
        ws.Range(ws.Cells(1, 1), ws.Cells(lastRow, gBomHeaders.Count)).WrapText = True
        ws.Range(ws.Cells(1, 1), ws.Cells(lastRow, gBomHeaders.Count)).VerticalAlignment = XL_TOP
        ws.Range(ws.Cells(1, 1), ws.Cells(lastRow, gBomHeaders.Count)).Borders.LineStyle = XL_CONTINUOUS
        ws.Range(ws.Cells(1, 1), ws.Cells(lastRow, gBomHeaders.Count)).Borders.Weight = XL_THIN
        ws.Range(ws.Cells(1, 1), ws.Cells(1, gBomHeaders.Count)).AutoFilter
    End If

    ws.Activate
    ws.Range("A2").Select
    ActiveWindowFreezePanesSafe
End Sub

Private Sub ActiveWindowFreezePanesSafe()
    On Error Resume Next
    Dim xl As Object
    Set xl = GetObject(, "Excel.Application")
    If Not xl Is Nothing Then
        xl.ActiveWindow.FreezePanes = True
    End If
End Sub

Private Sub InsertPictureIntoCell(ByVal ws As Object, ByVal imagePath As String, ByVal cell As Object)
    On Error GoTo InsertFailed

    Dim shp As Object
    Dim margin As Double
    Dim maxW As Double
    Dim maxH As Double

    margin = 4
    maxW = THUMBNAIL_WIDTH
    maxH = THUMBNAIL_HEIGHT
    If maxW > cell.Width - (2 * margin) Then maxW = cell.Width - (2 * margin)
    If maxH > cell.Height - (2 * margin) Then maxH = cell.Height - (2 * margin)
    If maxW < 10 Or maxH < 10 Then Exit Sub

    Set shp = ws.Shapes.AddPicture(imagePath, MSO_FALSE, MSO_TRUE, cell.Left + margin, cell.Top + margin, maxW, maxH)
    shp.LockAspectRatio = MSO_TRUE

    If shp.Width / maxW > shp.Height / maxH Then
        shp.Width = maxW
    Else
        shp.Height = maxH
    End If

    shp.Left = cell.Left + (cell.Width - shp.Width) / 2
    shp.Top = cell.Top + (cell.Height - shp.Height) / 2
    Exit Sub

InsertFailed:
    AddLog "", "WARNING", "Excel nije uspeo da ubaci sliku: " & imagePath & " | " & Err.Description, imagePath
    Err.Clear
End Sub

Private Sub InsertPictureIntoRange(ByVal ws As Object, ByVal imagePath As String, ByVal rangeAddress As String)
    On Error GoTo InsertFailed

    Dim rg As Object
    Set rg = ws.Range(rangeAddress)

    Dim shp As Object
    Set shp = ws.Shapes.AddPicture(imagePath, MSO_FALSE, MSO_TRUE, rg.Left + 4, rg.Top + 4, rg.Width - 8, rg.Height - 8)
    shp.LockAspectRatio = MSO_TRUE

    If shp.Width > rg.Width - 8 Then shp.Width = rg.Width - 8
    If shp.Height > rg.Height - 8 Then shp.Height = rg.Height - 8

    shp.Left = rg.Left + (rg.Width - shp.Width) / 2
    shp.Top = rg.Top + (rg.Height - shp.Height) / 2
    Exit Sub

InsertFailed:
    AddLog "", "WARNING", "Excel nije uspeo da ubaci summary sliku: " & Err.Description, imagePath
    Err.Clear
End Sub

Private Sub ApplyUsedRangeBorders(ByVal ws As Object)
    On Error Resume Next
    ws.UsedRange.Borders.LineStyle = XL_CONTINUOUS
    ws.UsedRange.Borders.Weight = XL_THIN
End Sub

Private Sub AddLog(ByVal partNumber As String, ByVal statusText As String, ByVal messageText As String, ByVal imagePath As String)
    On Error Resume Next
    Dim rec As Object
    Set rec = CreateObject("Scripting.Dictionary")
    rec.Add "DateTime", Now
    rec.Add "PartNumber", partNumber
    rec.Add "Status", statusText
    rec.Add "Message", messageText
    rec.Add "ImagePath", imagePath
    gExportLog.Add rec
End Sub

Private Function GetProductPartNumber(ByVal prod As Object) As String
    On Error Resume Next
    GetProductPartNumber = Trim$(CStr(prod.PartNumber))
    If GetProductPartNumber = "" Then GetProductPartNumber = GetPropertyValue(prod, "Part Number", "PartNumber", "PN")
    Err.Clear
End Function

Private Function GetProductRevision(ByVal prod As Object) As String
    On Error Resume Next
    GetProductRevision = Trim$(CStr(prod.Revision))
    If GetProductRevision = "" Then GetProductRevision = GetPropertyValue(prod, "Revision", "Revizija", "Rev")
    Err.Clear
End Function

Private Function GetProductNomenclature(ByVal prod As Object) As String
    On Error Resume Next
    GetProductNomenclature = Trim$(CStr(prod.Nomenclature))
    If GetProductNomenclature = "" Then GetProductNomenclature = GetPropertyValue(prod, "Nomenclature", "Nomenklatura", "Description", "Opis")
    Err.Clear
End Function

Private Function GetProductMass(ByVal prod As Object) As String
    On Error Resume Next

    Dim massFromProperty As String
    massFromProperty = GetPropertyValue(prod, "Mass", "Masa")
    If massFromProperty <> "" Then
        GetProductMass = massFromProperty
        Exit Function
    End If

    Dim analyzeObj As Object
    Dim m As Double
    Set analyzeObj = prod.Analyze
    m = CDbl(analyzeObj.Mass)
    If Err.Number = 0 And m <> 0 Then
        GetProductMass = Format$(m, "0.###")
    Else
        Err.Clear
        Dim refProd As Object
        Set refProd = prod.ReferenceProduct
        If Not refProd Is Nothing Then
            Set analyzeObj = refProd.Analyze
            m = CDbl(analyzeObj.Mass)
            If Err.Number = 0 And m <> 0 Then GetProductMass = Format$(m, "0.###")
        End If
    End If
    Err.Clear
End Function

Public Function GetPropertyValue(ByVal prod As Object, ParamArray propNames() As Variant) As String
    On Error Resume Next

    GetPropertyValue = TryGetPropertyValueFromProduct(prod, propNames)
    If GetPropertyValue <> "" Then Exit Function

    Dim refProd As Object
    Set refProd = prod.ReferenceProduct
    If Not refProd Is Nothing Then
        GetPropertyValue = TryGetPropertyValueFromProduct(refProd, propNames)
    End If
    Err.Clear
End Function

Private Function TryGetPropertyValueFromProduct(ByVal prod As Object, ByVal propNames As Variant) As String
    On Error Resume Next

    Dim v As String
    Dim props As Object
    Dim params As Object
    Dim nm As Variant

    Set props = prod.UserRefProperties
    If Not props Is Nothing Then
        For Each nm In propNames
            v = TryGetParameterValueByName(props, CStr(nm))
            If v <> "" Then
                TryGetPropertyValueFromProduct = v
                Exit Function
            End If
        Next nm
    End If

    Set params = prod.Parameters
    If Not params Is Nothing Then
        For Each nm In propNames
            v = TryGetParameterValueByName(params, CStr(nm))
            If v <> "" Then
                TryGetPropertyValueFromProduct = v
                Exit Function
            End If
        Next nm
    End If

    Err.Clear
End Function

Private Function TryGetParameterValueByName(ByVal params As Object, ByVal wantedName As String) As String
    On Error Resume Next

    Dim p As Object
    Dim v As String

    Set p = params.Item(wantedName)
    If Err.Number = 0 And Not p Is Nothing Then
        v = ParameterValueAsText(p)
        If v <> "" Then
            TryGetParameterValueByName = v
            Exit Function
        End If
    End If
    Err.Clear

    Dim i As Long
    For i = 1 To params.Count
        Set p = params.Item(i)
        If Err.Number = 0 And Not p Is Nothing Then
            If ParameterNameMatches(CStr(p.Name), wantedName) Then
                v = ParameterValueAsText(p)
                If v <> "" Then
                    TryGetParameterValueByName = v
                    Exit Function
                End If
            End If
        End If
        Err.Clear
    Next i
End Function

Private Function ParameterNameMatches(ByVal actualName As String, ByVal wantedName As String) As Boolean
    Dim a As String
    Dim w As String
    a = LCase$(Trim$(actualName))
    w = LCase$(Trim$(wantedName))

    ParameterNameMatches = (a = w Or Right$(a, Len(w) + 1) = "\" & w Or Right$(a, Len(w) + 1) = "/" & w)
End Function

Private Function ParameterValueAsText(ByVal p As Object) As String
    On Error Resume Next

    ParameterValueAsText = Trim$(CStr(p.ValueAsString))
    If ParameterValueAsText <> "" Then Exit Function

    Err.Clear
    ParameterValueAsText = Trim$(CStr(p.Value))
    If ParameterValueAsText <> "" Then Exit Function

    Err.Clear
End Function

Private Function GetProductBomType(ByVal prod As Object) As String
    If HasChildren(prod) Then
        GetProductBomType = "Assembly"
    Else
        GetProductBomType = "Part"
    End If
End Function

Private Function HasChildren(ByVal prod As Object) As Boolean
    On Error Resume Next
    Dim children As Object
    Set children = prod.Products
    HasChildren = (Err.Number = 0 And Not children Is Nothing And children.Count > 0)
    Err.Clear
End Function

Private Function IsProductObject(ByVal obj As Object) As Boolean
    On Error Resume Next
    Dim s As String
    s = CStr(obj.PartNumber)
    IsProductObject = (Err.Number = 0)
    Err.Clear
End Function

Private Function BuildUniqueImageFileName(ByVal partNumber As String, ByVal nomenclature As String, ByVal itemNo As Long) As String
    Dim baseName As String
    Dim ext As String
    Dim candidate As String
    Dim n As Long

    ext = EffectiveImageFormat()
    If ext = "" Then ext = "jpg"

    baseName = SafeFileName(Trim$(partNumber & "_" & nomenclature))
    If baseName = "" Or baseName = "_" Then baseName = "ITEM_" & Format$(itemNo, "0000")
    If Len(baseName) > 140 Then baseName = Left$(baseName, 140)

    candidate = baseName & "." & ext
    If SKIP_EXISTING_IMAGES And gFSO.FileExists(JoinPath(gImageFolder, candidate)) Then
        BuildUniqueImageFileName = candidate
        Exit Function
    End If

    n = 1
    Do While gFSO.FileExists(JoinPath(gImageFolder, candidate))
        candidate = baseName & "_" & Format$(n, "000") & "." & ext
        n = n + 1
    Loop

    BuildUniqueImageFileName = candidate
End Function

Private Function SafeFileName(ByVal valueText As String) As String
    Dim s As String
    Dim badChars As Variant
    Dim ch As Variant

    s = Trim$(valueText)
    badChars = Array("\", "/", ":", "*", "?", """", "<", ">", "|", vbTab, vbCr, vbLf)
    For Each ch In badChars
        s = Replace(s, CStr(ch), "_")
    Next ch

    Do While InStr(s, "__") > 0
        s = Replace(s, "__", "_")
    Loop

    If Len(s) > 180 Then s = Left$(s, 180)
    SafeFileName = Trim$(s)
End Function

Private Function SafeText(ByVal valueText As String) As String
    SafeText = Replace(Replace(Trim$(valueText), vbCr, " "), vbLf, " ")
End Function

Private Function FirstNonEmpty(ParamArray values() As Variant) As String
    Dim v As Variant
    For Each v In values
        If Trim$(CStr(v)) <> "" Then
            FirstNonEmpty = Trim$(CStr(v))
            Exit Function
        End If
    Next v
End Function

Private Function AppendNote(ByVal oldNote As String, ByVal addNote As String) As String
    If Trim$(oldNote) = "" Then
        AppendNote = addNote
    Else
        AppendNote = oldNote & " " & addNote
    End If
End Function

Private Function CloneCollection(ByVal source As Collection) As Collection
    Dim result As Collection
    Set result = New Collection

    Dim i As Long
    For i = 1 To source.Count
        result.Add source.Item(i)
    Next i

    Set CloneCollection = result
End Function

Private Sub EnsureFolder(ByVal folderPath As String)
    If Not gFSO.FolderExists(folderPath) Then gFSO.CreateFolder folderPath
End Sub

Private Function JoinPath(ByVal folderPath As String, ByVal childName As String) As String
    If Right$(folderPath, 1) = "\" Then
        JoinPath = folderPath & childName
    Else
        JoinPath = folderPath & "\" & childName
    End If
End Function

Private Function ReplaceFileExtension(ByVal filePath As String, ByVal newExt As String) As String
    Dim oldExt As String
    oldExt = gFSO.GetExtensionName(filePath)
    If Left$(newExt, 1) = "." Then newExt = Mid$(newExt, 2)
    If oldExt = "" Then
        ReplaceFileExtension = filePath & "." & newExt
    Else
        ReplaceFileExtension = Left$(filePath, Len(filePath) - Len(oldExt)) & newExt
    End If
End Function

Private Sub WaitSeconds(ByVal secondsToWait As Double)
    Dim startTime As Single
    Dim currentTime As Single

    startTime = Timer
    Do
        DoEvents
        currentTime = Timer
        If currentTime < startTime Then currentTime = currentTime + 86400!
    Loop While (currentTime - startTime) < CSng(secondsToWait)
End Sub

Private Function HasTimedOut(ByVal startTime As Double, ByVal timeoutSeconds As Double) As Boolean
    Dim currentTime As Double
    currentTime = Timer
    If currentTime < startTime Then currentTime = currentTime + 86400#
    HasTimedOut = ((currentTime - startTime) >= timeoutSeconds)
End Function

Private Function ImageTimeoutSeconds() As Double
    If FAST_SNIP_MODE Then
        ImageTimeoutSeconds = MAX_SECONDS_PER_IMAGE
    Else
        ImageTimeoutSeconds = IMAGE_EXPORT_TIMEOUT_SECONDS
    End If
End Function
